### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#1]
You've listed the dependencies GnuCOBOL 4.2+ (does not exist) and gdb 8.3+.
Is there a specific reason for the gdb version or should gdb 7.6+ work, too?

**Comment by OlegKunitsyn** [comment]
Thanks for input, fixed. 2.2 and 8.3 were installed on my system. Please try your versions.

**Comment by mitsakosgr** [comment]
Since you are using gdb mi2 interface, I think it is safe to recommend GDB 6.0+ instead of 8.3+.
[GDB Interpreters](https://sourceware.org/gdb/current/onlinedocs/gdb/Interpreters.html)

It is working fine with 7.6.1 I have right now.

**Comment by OlegKunitsyn** [comment]
> Since you are using gdb mi2 interface, I think it is safe to recommend GDB 6.0+ instead of 8.3+.
> [GDB Interpreters](https://sourceware.org/gdb/current/onlinedocs/gdb/Interpreters.html)
> 
> It is working fine with 7.6.1 I have right now.

Readme updated. Thanks!

**Comment by GitMensch** [comment]
Didn't you found out in another issue that GnuCOBOL 3.1 works fine, too? In this case it would be reasonable to remove it from the roadmap and specify 2.2+ in the dependencies again :-)

... if anyone has a repo-version of opencobol (that's 1.1) it would be "academically interesting" if this works, too.

**Comment by mitsakosgr** [comment]
It definitely works in 3.1 (I have on 3.1-dev now). But 3+ is either in dev or RC version. So it is preferably to stay on stable.

It is already mentioned as 2.2+ in [requirements](https://github.com/OlegKunitsyn/gnucobol-debug#requirements)!

**Comment by brunopacheco1** [comment]
I was testing on GC 3.0 and 3.1 Yesterday and the found issues were not related to the COBOL compiler so far. I'll keep testing today and finish reporting as soon as I have time. But I believe it can be removed from the roadmap.

**Comment by GitMensch** [comment]
> It is already mentioned as 2.2+ in [requirements](https://github.com/OlegKunitsyn/gnucobol-debug#requirements)!

That was the case, but it was changed to 2.2 and 3 placed on the roadmap - that was what my comment was about...

**Comment by mitsakosgr** [comment]
Ok, got it, sorry for the misunderstanding.
