### ISSUE TITLE
allow adjustment (or "add to") cobc arguments

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#10]
As it [currently stands](https://github.com/OlegKunitsyn/gnucobol-debug/blob/17b140e0bd07ec41df42a5e35f1bd5bd40e8288d/src/mi2.ts#L70) the cobc arguments are hard wired. This was brought up by @mitsakosgr in https://github.com/OlegKunitsyn/gnucobol-debug/issues/6#issuecomment-618904449.
This is bad because of multiple reasons:

* addition of more arguments, for example to specify include paths, linking options, ... is not possible
* debugging lines are always active (this is a reasonable default, but it should not be enforced)
* currently `-free` is hard-wired, breaking a guessed amount of ~80% existing COBOL code, including most tutorials (as those use fixed-form reference-format)
* currently `-x` is hard-wired, breaking compilation of every sub-program
* it is not possible to specify a dialect or dialect/reserved word options, so again some source may not compile or behave different than expected

FR: allow to change the compile commands via launch.json or otherwise with reasonable defaults and likely also a set of flags that is normally _not possible to override_ (like `-g`, which implies `-fsource-location` btw); possibly a yes/no for "fixed-form", "debugging-lines", and `-d` [enable all runtime-checks].

**Comment by mitsakosgr** [comment]
I think that -g is required for the generated files.

**Comment by GitMensch** [comment]
> I think that -g is required for the generated files.

Totally, this was just a typo, I meant `-d` (edited above)

**Comment by GitMensch** [comment]
@OlegKunitsyn  Please reopen as `-d` (enable all runtime checks) and `-fdebugging-line` (enable all debugging lines in the code) are a reasonable default, but should be changeable via launch.json

**Comment by OlegKunitsyn** [comment]
Fixed
