### ISSUE TITLE
Badges broken?

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#109]
Currently only Node.js CI test badges are shown, the others don't render something valid and opening them leads to errors.

**Comment by OlegKunitsyn** [comment]
Yes. https://vsmarketplacebadge.apphb.com/

**Comment by GitMensch** [comment]
@OlegKunitsyn Hm, this is closed but the badges are still broken, seems the following is related https://github.com/cssho/VSMarketplaceBadge/issues/18, what about directly using the badges from [Shields.io](https://shields.io/)?

**Comment by GitMensch** [comment]
@OlegKunitsyn If you agree to directly move to shields.io just reopen and assign to me and I'll PR a tested version.

**Comment by OlegKunitsyn** [comment]
Thank you.

**Comment by GitMensch** [comment]
Fixed by a6cda21f8f2bde3e36ee917480da6b4a65e424a2.
