### ISSUE TITLE
allow to specify arguments for starting

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#12]
[This is possibly only a documentation issue and was split out from #10]

It would be good to be able to pass arguments to the running program, for example by launch.json which likely also provides a way to "ask" for the arguments while remembering the last one entered.

Those arguments would then need to be passed to GDB as run args. (the program would use them either with `PROCEDURE DIVISION CHAINING` or by `ACCEPT FROM ARGUMENT-VALUE`).

**Comment by OlegKunitsyn** [comment]
Implemented by https://github.com/OlegKunitsyn/gnucobol-debug/commit/c8d261aae1e428b39ced856c56362363d773a86c
