### ISSUE TITLE
Updated docker environment for gnucobol 3.2?

### ISSUE THREAD

**Issue by Smitty2018** [OlegKunitsyn/gnucobol-debug#128]
There was a "3.2 preview" release, can you update the docker environment please?

**Comment by OlegKunitsyn** [comment]
Please set your favorite docker image in `docker`, see https://github.com/OlegKunitsyn/gnucobol-debug#docker for details.

**Comment by GitMensch** [comment]
I _think_ this was about adding the 3.2 preview to https://hub.docker.com/r/olegkunitsyn/gnucobol/tags; it may be a good idea to do so once 3.2 RC3 is out, which should be end of this week.
