### ISSUE TITLE
option to debug programs compiled as module

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#13]
[This was split out from #10]

It would be good to be able to specify via configuration that a source file is not compiled as executable (currently hard wired `-x`).  If this is available gdb must invoke `cobcrun` instead of the program and pass the module name as first run argument, so both "compile" and "debug" are to be changed here.

Furthermore it would be good to also debug sub-programs (this may should be moved to a different issue).
In this scenario one would compile different modules beforehand and then start debugging on the main program - to even simplify this (many people work with the same main program for a long time and only debug changing sub-programs) it could be good to be able to specify the main program via launch.json (this may be possible already and just needs some sample documentation).

**Comment by GitMensch** [comment]
Second thought: I'd suggest to not use `-x` at all and *always* start GDB with `cobcrun` as this brings more flexibility in general.

**Comment by OlegKunitsyn** [comment]
`-x` is configurable (removable) in `launch.json` since v. 0.8.22

**Comment by GitMensch** [comment]
@OlegKunitsyn as mentioned previously this would only work if gdb is started with `cobcrun name` instead of `name`. Can we already configure this? If yes it would be good to mention in the docs, if not it may be reasonable to *always* use `cobcrun` and not support `-x` at all.

**Comment by mitsakosgr** [comment]
How can gdb use breakpoints from cobol source (or .c source), while running cobcrun?

I am not a regular gdb user, so I am trying to find a way to add breakpoints to .c file and run `gdb cobcrun` and stop at those breakpoints.

An example would be great!

**Comment by GitMensch** [comment]
> How can gdb use breakpoints from cobol source (or .c source), while running cobcrun?

Because `cobcrun` loads the C or COBOL module and therefore GDB will execute and can find those. It is the same as if a COBOL program would do a `CALL` (or `vim` loads an extension [you'd debug it by starting vim, too], or similar).

**Comment by GitMensch** [comment]
@OlegKunitsyn I think this one should be re-opened. As there's still only debugging of $target so if you remove -x from the cobc options you cannot debug the result.

I suggest to add `cobcrunpath` to the entrires, remove `-x` from the cobc options and document that it should not be used and change the gdb invocation to use cobcrunpath as target with the (previous, real) target as run argument.

**Comment by GitMensch** [comment]
@OlegKunitsyn I've just tested this but I cannot get debugging of a single module which is not a main to work with this extension.
It looks like the `target`attribute is both used for compilation (where `$(file)` is correct) and for debugging (where `cobcrun` would be correct). Please either reopen or explain (ideally with a sample in the README to prevent this question in the future).

**Comment by GitMensch** [comment]
I've tried the caller **workaround** (something I don't like to use):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "target": "${file}",
            "targetargs": [],
            "cwd": "${workspaceRoot}",
            "gdbpath": "gdb",
            "cobcpath": "cobc",
            "cobcargs": [
                "-debug",
                "-fdump=ALL",
                "-x"
            ],
            "group": ["CBL_OC_DUMP.cob"]
        }
    ]
}
```

with the result

> Could not start debugger process
/home/simon/gnucobol-3.x/extras/caller.cob: cobc: CBL_OC_DUMP.cob file not found

**Comment by GitMensch** [comment]
@OlegKunitsyn please reopen, this is still not solved as `cobcrun´ is still not used.
I suggest the following:
* remove `-x` from the default cobcargs
* add a new attribute "executable" 
    * if "true" (I highly suggest to default to "false"), then add `-x` to the compile args
    * if "false" start the program after adjusting `target = 'cobcrun' + isWin32 ? '.exe ' : ' ' + target`
