### ISSUE TITLE
Task definition does not work

### ISSUE THREAD

**Issue by PaoloRicardo** [OlegKunitsyn/gnucobol-debug#135]
I am using a Task definition to compile GnuCOBOL code. I have a task definition thus:
<{
 "version": "2.0.0",
 "options": {
   "env": {
     "PATH": "\\gnucobol\\bin",
     "COB_CONFIG_DIR": "c:\\gnucobol\\config",
     "COB_COPY_DIR": "c:\\gnucobol\\copy",
     "COB_INCLUDE_PATH": "c:\\gnucobol\\include",
     "COB_LIB_PATH": "c:\\gnucobol\\lib",
   "cwd": "${fileDirnameBasename}" }
 },
 "tasks": [
  {
    "label": "GnuCOBOL - Compile",
    "type": "shell",
    "command": "cobc",
    "args": [
      "-x",
      "-std=mf",
      "${file}"
    ],
    "problemMatcher": "$gnucobol-cobc",
    "group": {
      "kind": "build",
      "isDefault": true
    }
  }
]
}>
  My source code is in: c:\workarea\gnucobol\beeb and the program is BBCB.CBL. When I run the Task I expected BBCB.EXE to be placed in c:\workarea\gnucobl\beeb. Instead it is placed in c:\vscode.
Have I missed a setting or am I doing something wrong?

**Comment by GitMensch** [comment]
Where is this real definition stored?

Just to recheck: Do you execute the build task when you have the file open?

Note: you likely could add -o parameter to the cobc invocation to get the expected result in any case.

**Comment by PaoloRicardo** [comment]
Yes, via Terminal -> RunTask.

I added -o as a parameter and that put the .exe file in the expected directory. Ideally, though, I don't really want to hard code the output file name in the task.

**Comment by GitMensch** [comment]
no hardcoding, but something like

```json
    "-o",
    "${fileDirname}/${fileBasenameNoExtension}.exe"
```

,.. but I guess I've spot the issue in your original definition when looking at this along with the [vscode task variable-reference](https://code.visualstudio.com/docs/editor/variables-reference):

you've used `"cwd": "${fileDirnameBasename}"`, but that won't result in an existing directory; I _guess_ you wantd to use `"cwd": "${fileDirname}"`; doing so should then drop the need to specify `-o` at all.

Please verify if that is the case, if it is it would be good to post an answer on your StackOverflow question about this, too.

**Comment by PaoloRicardo** [comment]
Yes, via Terminal -> RunTask.

I added -o as a parameter and that put the .exe file in the expected directory. Ideally, though, I don't really want to hard code the output file name in the task.

**Comment by PaoloRicardo** [comment]
This is the 'tasks' section amended:

"tasks": [
  {
    "label": "GnuCOBOL - Compile",
    "type": "shell",
    "command": "cobc",
    "args": [
      "-x",
      "-std=mf",
      "cwd": "${fileDirname}",    <-- the : has a wiggly line under it denoting problem
      "${file}",
      "${fileDirname}/${fileBasenameNoExtension}.exe" 
    ],
    "problemMatcher": "$gnucobol-cobc",
    "group": {
      "kind": "build",
      "isDefault": true
    }
  }
]

When I run the task I get this message:

cobc: cwd: No such file or directory

 *  The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command cobc -x -std=mf cwd C:\WORKAREA\VSCodium C:\WORKAREA\VSCodium\cursor.cbl C:\WORKAREA\VSCodium/cursor.exe" terminated with exit code: 1.

**Comment by GitMensch** [comment]
Replace the cwd that you have easier with the wiggle line...

**Comment by PaoloRicardo** [comment]
This is the 'tasks' section amended:

"tasks": [
  {
    "label": "GnuCOBOL - Compile",
    "type": "shell",
    "command": "cobc",
    "args": [
      "-x",
      "-std=mf",
      "cwd": "${fileDirname}",    <-- the : has a wiggly line under it denoting problem
      "${file}",
      "${fileDirname}/${fileBasenameNoExtension}.exe" 
    ],
    "problemMatcher": "$gnucobol-cobc",
    "group": {
      "kind": "build",
      "isDefault": true
    }
  }
]

When I run the task I get this message:

cobc: cwd: No such file or directory

 *  The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command cobc -x -std=mf cwd C:\WORKAREA\VSCodium C:\WORKAREA\VSCodium\cursor.cbl C:\WORKAREA\VSCodium/cursor.exe" terminated with exit code: 1.

**Comment by PaoloRicardo** [comment]
Herewith my tasks.json which now correctly places the .exe file in the same folder as the .cbl source file. Thanks for your help:

{
 "version": "2.0.0",
 "options": {
   "env": {
     "PATH": "\\gnucobol\\bin",
     "COB_CONFIG_DIR": "c:\\gnucobol\\config",
     "COB_COPY_DIR": "c:\\gnucobol\\copy",
     "COB_INCLUDE_PATH": "c:\\gnucobol\\include",
     "COB_LIB_PATH": "c:\\gnucobol\\lib"
       }
 },
 "tasks": [
  {
    "label": "GnuCOBOL - Compile",
    "type": "shell",
    "command": "cobc",
    "args": [
      "-x",
      "-std=mf-strict",
      "-tPROGLST",
      "-fformat=COBOL85",
      "${file}"
    ],
    "group": {
      "kind": "build",
      "isDefault": true
    }
  }
]
}

**Comment by PaoloRicardo** [comment]
The 'env' paths should be \\ not \. Submitting the comment strips one of them.
