### ISSUE TITLE
Removing -x from cobc args breaks extension

### ISSUE THREAD

**Issue by mitsakosgr** [OlegKunitsyn/gnucobol-debug#14]
0.7.22
Removing -x from default cobc arguments breaks the extension, because gdb is not able to find the executable to debug.

See #11 and #13

**Comment by OlegKunitsyn** [comment]
fixed in 0.8.22

**Comment by mitsakosgr** [comment]
This is not ideal, because a user could easily remove it, thinking that it works without it.

Maybe add it to mi2.ts, until a patch that supports both modes is available.
