### ISSUE TITLE
Hidden stdout inside PERFORM

### ISSUE THREAD

**Issue by OlegKunitsyn** [OlegKunitsyn/gnucobol-debug#15]
Compare execution and debugging modes of test/resources/petstore.cbl

**Comment by OlegKunitsyn** [comment]
Fixed by https://github.com/OlegKunitsyn/gnucobol-debug/commit/c8d261aae1e428b39ced856c56362363d773a86c

**Comment by GitMensch** [comment]
Just in case you don't know yet @OlegKunitsyn - it is always good to reference the issues that related by "#issuenumber" in the commit message, as this will provide an automated backlink,
If you use something like "fixes #issuenumer" the issue will also automatically be closed.

Note; c8d261a is really a nice one!
