### ISSUE TITLE
Is the stop on breakpoint broken?

### ISSUE THREAD

**Issue by gfmoore** [OlegKunitsyn/gnucobol-debug#16]
v0.22.9
Hi, very sorry, I've probably done something wrong, but the debugger doesn't seem to stop on the breakpoint now (but it did.) I did create a new launch.json and I've tried with F5 and ctrl-F5, and from the visual icon but the code just runs through to the end and doesn't stop on the breakpoint.

![image](https://user-images.githubusercontent.com/22768967/80402095-4d909300-88b5-11ea-863f-6253df360858.png)

![image](https://user-images.githubusercontent.com/22768967/80402203-7add4100-88b5-11ea-96ca-9dcdda26bf17.png)

Noted this when using F5
![image](https://user-images.githubusercontent.com/22768967/80402520-ec1cf400-88b5-11ea-9137-73aa107bd2df.png)

**Comment by OlegKunitsyn** [comment]
Please attach your program and describe the system.

**Comment by gfmoore** [comment]
I assume this is what you want
gdb --version
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Ubuntu 18.04 on Windows 10 2004, wsl 2 slow insider ring


cobol debugger 0.22.10

launch.json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "COBOL debugger",
      "type": "gdb",
      "request": "launch",
      "target": "${file}",
      "targetargs": [],
      "cwd": "${workspaceRoot}",
      "gdbpath": "gdb",
      "cobcpath": "cobc",
      "cobcargs": [
        "-free",
        "-x",
        "-fgen-c-line-directives"
      ],
      "group": []
    }
  ]
}


Code:
       IDENTIFICATION DIVISION.
       
       PROGRAM-ID.         Sample1.
       AUTHOR.             Gordon Moore.
       
       ENVIRONMENT DIVISION.
       
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-NUMA          PIC 9(3).
       01 WS-NUMB          PIC 9(3).
       01 WS-NUMC          PIC 9(4).
       
       PROCEDURE DIVISION.
           MOVE 100 TO WS-NUMA.
           MOVE 200 TO WS-NUMB.
           COMPUTE WS-NUMC = WS-NUMA + WS-NUMB.
           DISPLAY "A-VALUE ", WS-NUMA. 
           DISPLAY "B-VALUE ", WS-NUMB.
           DISPLAY "C-VALUE ", WS-NUMC.
           STOP RUN. 

I'll attach as txt

[Sample.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4547339/Sample.txt)

Output with F5
![image](https://user-images.githubusercontent.com/22768967/80515747-56976800-897a-11ea-9ccc-7eeaa532419f.png)

Output with ctrl F5

![image](https://user-images.githubusercontent.com/22768967/80515812-74fd6380-897a-11ea-9cd9-69f9d745bd1f.png)


Anything else?

**Comment by OlegKunitsyn** [comment]
`-fgen-c-line-directives` not supported by cobc v 2.2. I guess you have old C files. Remove them please.

**Comment by gfmoore** [comment]
uh oh,
realised I hadn't done a gnucobol version, went to do it and it says command not found, and yet program  is compiling??? I downloaded the latest gnucobol and did the compile and make myself as gnucobol isn't in the Ubuntu 18.04 repository for some reason, though opencobol is.

Let me go and figure this out - it doesn't make sense.

**Comment by gfmoore** [comment]
Oh I'm a right dimwod, it's cobc

cobc --version
cobc (GnuCOBOL) 3.1-dev.0
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Keisuke Nishida, Roger While, Ron Norman, Simon Sobisch, Edward Hart
Built     Apr 24 2020 08:42:45
Packaged  Apr 23 2020 14:55:23 UTC
C version "7.5.0"

**Comment by OlegKunitsyn** [comment]
Okay, I've updated Readme. GnuCOBOL 3 has been added to the roadmap.

**Comment by gfmoore** [comment]
Removed anything other than sample.cob
No change. Compiles, but doesn't stop on breakpoint.
Someone did ask me to download the cobc 3.1 a few days ago, which I duly did. Do you want me to download and make an earlier version? (I wish I could gnucobol using apt?)

**Comment by OlegKunitsyn** [comment]
I assume that the extension is incompatible with cobc 3.

**Comment by gfmoore** [comment]
I bet your not allowed to do this, but
![2020-04-28-start-from-scratch](https://user-images.githubusercontent.com/22768967/80517256-b262f080-897c-11ea-9cc4-ef1b60ee0a07.jpg)
From https://www.howtogeek.com/wp-content/uploads/2020/04/2020-04-28-start-from-scratch.jpg

**Comment by gfmoore** [comment]
Why? It compiles. AFAIK cob or cbl are both perfectly acceptable extensions to gnucobol? But give me a minute and I'll change it :)

regards,

Gordon
gm@gordonmoore.co.uk

On 28/04/2020 18:18:02, OlegKunitsyn <notifications@github.com> wrote:
I assume that the extension is incompatible with cobc 3.

**Comment by gfmoore** [comment]
No, no difference using .cbl, sorry.

regards,

Gordon
gm@gordonmoore.co.uk

On 28/04/2020 18:18:02, OlegKunitsyn <notifications@github.com> wrote:
I assume that the extension is incompatible with cobc 3.

**Comment by GitMensch** [comment]
> 
> 
> `-fgen-c-line-directives` not supported by cobc v 2.2. I guess you have old C files. Remove them please.

Completely correct, that is a very recent 3.1-dev option which *may* help to get better breakpoints (or totally confuse the extension).
I see no reason that GC3.1 should not work with this extention.

**Comment by brunopacheco1** [comment]
Hi @gfmoore , are you still facing this issue? If yes, you have some options to follow:

- Downgrade your gnucobol to 2.2. Perhaps the one available on Ubuntu repo is called opencobol, but it doesn't matter if it is 2.2;
- Double-check the debugger launcher, following the README (probably you'll have to remove "-free" arg if you are not using the free form);
- Enable the debugger verbose mode, to have more details (howto described on README);
- Double-check the language support extension you have installed, it is required to enable debugging mode;

**Comment by brunopacheco1** [comment]
Hi again, I was trying out the GC 3.1 and it looks like it is working fine, as it was working before on 2.2, so your issue could be a mistake on VSCode configuration. Please, check again the debugger launcher and the language support you have installed on VSCode.

**Comment by gfmoore** [comment]
I've attached a verbose debug output (run from F5, ctrl f5 just runs, no issues, but not stopping.
[debugverbose.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4548569/debugverbose.txt)
I don't know what I'm looking for, but I nted an error line at around line 32, 34

The other extensions are the bitlang source colouriser 6.2.5 and the Broadcom language support 0.11.1

At the moment this is not a major issue yet as I'm only just learning COBOL so I can do debugging the old fashioned way - manual input and output, but no doubt someone who has a real need will need this.

btw is there a simple way to remove the gnucompiler if compiled from source or do you just "make etc" the downloaded older version and it overwrites the newer one? I'm a bit of a newbie to this sort of thing with Linux :)

Thanks for all your efforts at any rate.

**Comment by gfmoore** [comment]
I know I've posted this before, but is this error bar at bottom right significant? It would be interesting to know what it means and why it occurs? Can't be right?
![image](https://user-images.githubusercontent.com/22768967/80540419-2fa05c80-89a1-11ea-8740-a024c155086f.png)

**Comment by brunopacheco1** [comment]
To uninstall move into the source folder and run "sudo make uninstall" and then "sudo ldconfig".
BTW, how did you install the gnucobol? Could you list the commands you've used?


On Tuesday, April 28, 2020, 11:33 PM, Gordon Moore <notifications@github.com> wrote:




I've attached a verbose debug output (run from F5, ctrl f5 just runs, no issues, but not stopping.
debugverbose.txt
I don't know what I'm looking for, but I nted an error line at around line 32, 34

The other extensions are the bitlang source colouriser 6.2.5 and the Broadcom language support 0.11.1

At the moment this is not a major issue yet as I'm only just learning COBOL so I can do debugging the old fashioned way - manual input and output, but no doubt someone who has a real need will need this.

btw is there a simple way to remove the gnucompiler if compiled from source or do you just "make etc" the downloaded older version and it overwrites the newer one? I'm a bit of a newbie to this sort of thing with Linux :)

Thanks for all your efforts at any rate.

**Comment by gfmoore** [comment]
The commands were from the gnuCobol FAQ. I'll look them up tomorrow, but for now it's time for bed :)

**Comment by gfmoore** [comment]
I downloaded a different version, but 
![image](https://user-images.githubusercontent.com/22768967/80569683-56867f00-89f1-11ea-9006-d0ef75005fcc.png)

**Comment by gfmoore** [comment]
I also noted these comments and did the export. Of course gnucobol is not in the 18.04 repository
![image](https://user-images.githubusercontent.com/22768967/80569910-c09f2400-89f1-11ea-805e-07edbd116faf.png)

**Comment by gfmoore** [comment]
Ok so I downgraded to gnucobol 2.2 rebuilt the json, remove the free and the fgen line, but still the same issue, it compiles fine, produces output and does NOT stop on the debug point.
 If Bruno got it to work, then I'm stumped here. It must be something to do with my setup, but to be honest that doesn't make much sense to me.

So remember I'm using win10, window subsystem for linux (wsl) 2, and opening a bash shell and running code . to run the vs code. I think it's running a linux version of vs code, but I don't know how to test that.

I suppose one good thing is that I've now learnt how to make and install from source code - yay!

Oh and I used the petshop prog.

![image](https://user-images.githubusercontent.com/22768967/80575995-517afd00-89fc-11ea-8022-b73c3d87f219.png)

Here's the launch.json
![image](https://user-images.githubusercontent.com/22768967/80576029-62c40980-89fc-11ea-9383-f054301830d0.png)

:(

**Comment by GitMensch** [comment]
> So remember I'm using win10, window subsystem for linux (wsl) 2

Windows support is in the roadmap and I assume the WSL2-stuff may or may not work (if it does you'd likely have to set up different other stuff, possibly including proprietary WSL plugins, before).

> and opening a bash shell and running code . to run the vs code. I think it's running a linux version of vs code, but I don't know how to test that.

Open the task manager [CTRL]+[SHIFT]+[ESC], go to Details tab, if you have "VSCode,exe",/"VSCodium.exe" (or similar) you have a Windows version (which is very likely); if you have "vscode" or "vscodium" (no .exe) then you have a WSL-version of it running.

**Comment by gfmoore** [comment]
Nothing is ever what it seems?
:)
![image](https://user-images.githubusercontent.com/22768967/80579505-0c59c980-8a02-11ea-8671-9487aa0c046e.png)
![image](https://user-images.githubusercontent.com/22768967/80579560-2c898880-8a02-11ea-8c99-04f557e3fac2.png)

**Comment by gfmoore** [comment]
I'll add the expanded view from the main tab just for fun
![image](https://user-images.githubusercontent.com/22768967/80579804-8a1dd500-8a02-11ea-83f9-9a4cff9aae42.png)

**Comment by gfmoore** [comment]
Here's a question or two :)
I'm looking at how gdb works - well it's interesting and educational I suppose :)
How does the debugger/gdb map the line number in the COBOL source file in vs-code to the line number in the executable? that gdb knows about?- cause they aren't the same. Oh and gdb will debug my code fine - once I worked out where to put the breakpoints.

The second question is back to this error message - sorry to keep harping on about it, but I feel it is important!
![image](https://user-images.githubusercontent.com/22768967/80585614-90fd1580-8a0b-11ea-9580-28fda3956bfc.png)
What is generating this? Is it gdb or the vs code COBOL debugger code? I've only found one reference in search to anything similar and that talks about a source file starting with a number/decimal and this isn't the case here.

**Comment by gfmoore** [comment]
The error is thrown from gdb. I found this in the gdb code
![image](https://user-images.githubusercontent.com/22768967/80586421-d79f3f80-8a0c-11ea-818d-4a139c23f58e.png)

ref: https://github.com/espressif/binutils-esp32ulp/blob/master/gdb/linespec.c

**Comment by gfmoore** [comment]
Does this add to the issue?
![image](https://user-images.githubusercontent.com/22768967/80587091-e0444580-8a0d-11ea-9547-6b871c1f0d3c.png)

**Comment by gfmoore** [comment]
In the verbose output here are the lines causing a problem
addBreakPoint 
stdin: 7-break-insert -f ":0"
addBreakPoint 
stdin: 8-break-insert -f ":0"
stdout: 7^error,msg="malformed linespec error: unexpected colon"
(gdb) 
GDB -> App: {"token":7,"outOfBandRecord":[],"resultRecords":{"resultClass":"error","results":[["msg","malformed linespec error: unexpected colon"]]}}
stdout: 8^error,msg="malformed linespec error: unexpected colon"
(gdb) 
GDB -> App: {"token":8,"outOfBandRecord":[],"resultRecords":{"resultClass":"error","results":[["msg","malformed linespec error: unexpected colon"]]}}
stdin: 9-exec-run

So, as I read it, when a breakpoint is added (and I don't know why there are two?) gdb is saying sorry there's a colon that I don't understand, so I'm not adding the breakpoint!, but I'll carry on and run your program.

So my question now is, where does this colon come from. Unfortunately I have no idea how to debug the COBOL debugger! It looks like it's written in TypeScript, but apart from that...

**Comment by gfmoore** [comment]
Here is one place where a colon is added
![image](https://user-images.githubusercontent.com/22768967/80591342-75970800-8a15-11ea-8190-0577af77197b.png)

**Comment by gfmoore** [comment]
Sorry mi2.ts

**Comment by gfmoore** [comment]
location += '"' + escape(map.fileC) + ":" + map.lineC + '"';
I'm looking at gdb linespec, not that I really understood it, but is perhaps map.lineC returning a null or blank?
I'd need to debug the code, it's as much as I can do here - over to you :)

**Comment by GitMensch** [comment]
> So my question now is, where does this colon come from.

I *guess* that comes from the plugin that "triggers" GDB and it is using the unchanged file's fullname - which is, on VSCode.exe something like "C:\Users\you\Desktop\test.cob".

To let it work with WSL it would be likely enough to have the file passed after `wslpath` was applied (so the above path is internally translated to `/mnt/c/Users/you/Desktop/test.cob), but it likely would also work if the filename is used, instead of the path name..

**Comment by brunopacheco1** [comment]
> In the verbose output here are the lines causing a problem
> addBreakPoint
> stdin: 7-break-insert -f ":0"
> addBreakPoint
> stdin: 8-break-insert -f ":0"
> stdout: 7^error,msg="malformed linespec error: unexpected colon"
> (gdb)
> GDB -> App: {"token":7,"outOfBandRecord":[],"resultRecords":{"resultClass":"error","results":[["msg","malformed linespec error: unexpected colon"]]}}
> stdout: 8^error,msg="malformed linespec error: unexpected colon"
> (gdb)
> GDB -> App: {"token":8,"outOfBandRecord":[],"resultRecords":{"resultClass":"error","results":[["msg","malformed linespec error: unexpected colon"]]}}
> stdin: 9-exec-run
> 
> So, as I read it, when a breakpoint is added (and I don't know why there are two?) gdb is saying sorry there's a colon that I don't understand, so I'm not adding the breakpoint!, but I'll carry on and run your program.
> 
> So my question now is, where does this colon come from. Unfortunately I have no idea how to debug the COBOL debugger! It looks like it's written in TypeScript, but apart from that...

I am facing a similar bug when testing the debugger on a MacOS, I'm opening a new issue Mac OS support.

**Comment by gfmoore** [comment]
I know you are probably sick of me here, but I'm trying to set us vs code to debug the cobol-debugger and I'm getting a promise error on a folder called /home/gordon/.zowe
It looks like zowe is some kind of document manager! Do I need to install it, do I want it? , where can I disable whatever is looking or it?

**Comment by brunopacheco1** [comment]
> > So my question now is, where does this colon come from.
> 
> I _guess_ that comes from the plugin that "triggers" GDB and it is using the unchanged file's fullname - which is, on VSCode.exe something like "C:\Users\you\Desktop\test.cob".
> 
> To let it work with WSL it would be likely enough to have the file passed after `wslpath` was applied (so the above path is internally translated to `/mnt/c/Users/you/Desktop/test.cob), but it likely would also work if the filename is used, instead of the path name..

There's another colon concatenation, mi2.ts:404.

**Comment by GitMensch** [comment]
> where can I disable whatever is looking or it?

disable the other extensions

**Comment by brunopacheco1** [comment]
> > > So my question now is, where does this colon come from.
> > 
> > 
> > I _guess_ that comes from the plugin that "triggers" GDB and it is using the unchanged file's fullname - which is, on VSCode.exe something like "C:\Users\you\Desktop\test.cob".
> > To let it work with WSL it would be likely enough to have the file passed after `wslpath` was applied (so the above path is internally translated to `/mnt/c/Users/you/Desktop/test.cob), but it likely would also work if the filename is used, instead of the path name..
> 
> There's another colon concatenation, mi2.ts:404.

Actually the bug is indeed in the line mentioned before, it looks like the GDB is not accepting the breakpoint insertion, it's supposed to have the colon there as it refers to the line to insert the breakpoint. Perhaps the file to attach the breakpoint is not visible to the GDB.

**Comment by gfmoore** [comment]
I can't get debug-cobol code to debug. It compiles, runs a vs code instance with my program and breakpoint. I run that, but just as before. i try and set a breakpoint in the cobol debugger code and it just says breakpoint set but not yet bound.
The promise error came from the Broadcom cobol language support - which I disabled - no difference apart from no error on the promise.

I've tried writing out console statements, but the code doesn't seem to get activated, but I'm losing touch with reality here. It may be that the debug of cobol-debugger is exactly what should be happening, but not what I would have expected. 
@Bruno, did you get the vscode setup and running to debug the cobol-debugger code?
![image](https://user-images.githubusercontent.com/22768967/80612732-480d8700-8a34-11ea-866c-68105b81657e.png)

**Comment by gfmoore** [comment]
Maybe the add-breakpoint isn't getting called properly, I don't know :frustrated

**Comment by brunopacheco1** [comment]
Okay, I think I understand what is going on. For some reason, the debugger has kept old breakpoints or is adding arbitrarily, which leads us to the :0 malformed error.

Please @gfmoore remove all breakpoints you have listed in the debugger and then add again the breakpoint in the line you want.

**Comment by brunopacheco1** [comment]
According to gdb documentation, the break-insert command accepts the line as an argument, which means file:linenumber, if there's no file, in this case of ":0", this error message is thrown.

**Comment by brunopacheco1** [comment]
@gfmoore I forgot to answer your question, I had the same issue "breakpoint set but not yet bound", but I could console.log, there's a method called log on this MI2 class. If you type something like `this.log('stdout', 'my log');`, but it is going to log into the COBOL code debugger console, not in the extension debugger console.

I fill like living the Inception movie right now.

**Comment by OlegKunitsyn** [comment]
The root cause has been spotted and fixed in 0.22.11. Please confirm.

**Comment by OlegKunitsyn** [comment]
> ...unexpected colon...

The message is annoying but harmless. The source-map returns non-existing cobol line ('', 0) to gdb during the navigation inside C sources aka Step *.

**Comment by gfmoore** [comment]
Way to go.

Can I ask, just for my own information, was I getting anywhere close or was I off on the wrong track?

**Comment by OlegKunitsyn** [comment]
It was 2 missing chars in the regex.

**Comment by gfmoore** [comment]
Ha, I'd never have found that! A tricky bug to find. Well done and thank-you for all your efforts.
It wasn't a waste of time for me though as I learnt a lot of things I'd never had to deal with before.
it's a long way since Fortran IV in the 70s eh. :)

**Comment by OlegKunitsyn** [comment]
The best thing (besides of your feedbacks) you guys can do, is a [short review](https://marketplace.visualstudio.com/items?itemName=OlegKunitsyn.gnucobol-debug&ssr=false#review-details). And 5 stars of course. The promotion helps bring more contributors, new features and quality improvements. :seedling:

**Comment by gfmoore** [comment]
did it a few days ago! :)

regards,

Gordon
gm@gordonmoore.co.uk

On 30/04/2020 15:07:59, OlegKunitsyn <notifications@github.com> wrote:
The best thing (besides of your feedbacks) you guys can do, is a short review [https://marketplace.visualstudio.com/items?itemName=OlegKunitsyn.gnucobol-debug&amp;ssr=false#review-details]. And 5 stars of course. The promotion helps bring more contributors, new features and quality improvements. 🌱
