### ISSUE TITLE
Debugger ignores step over in the end of a function call

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#17]
Cobol debugger - latest
cobc (GnuCOBOL) 2.2.0
GNU gdb (Debian 8.2.1-2+b3) 8.2.1

After stepping over 1 or 2 times (depending on the inputs), on line 107, the debugger releases the breakpoint and finishes the code execution (as it has no other breakpoint after).

It is not a big issue though, but I'm used to not release the breakpoint until I say so, or when the program really exits.

[Sample code](https://github.com/brunopacheco1/cobol-hello-world/blob/master/petstore.cbl)

![image](https://user-images.githubusercontent.com/4491850/80528431-35dd0b80-8996-11ea-936e-ed65fbfc07c5.png)

**Comment by brunopacheco1** [comment]
I believe there is a mistake in the actions, by accident I hit the "step into" button and it worked as the step over and it kept the breakpoint execution, after finishing the 0004-CALCULATE-DISCOUNT.

**Comment by OlegKunitsyn** [comment]
Yes, possible. The extension does not analyse an execution graph. You may try different combinations by stepping inside the sample.cbl -> subsample.cbl -> subsubsample.cbl chain.

**Comment by brunopacheco1** [comment]
I was facing some strange issues related to WSL, so I couldn't debug properly the extension.

Tomorrow I'll try to double-check this, but the behavior on StepOver should be the same as StepInto, when reaching the end of the loop. So, perhaps instead of commanding "exec-next", to the next source line, it should be "exec-step". 

At least reading the C it looks there is a way to return to the top of the PERFORM stack call when finishing the loop. Maybe there is a way to capture the same info and do the same here.

**Comment by OlegKunitsyn** [comment]
Please try to test the extension and change line 252 of mi2.ts to `this.stepOut();`, too.

**Comment by brunopacheco1** [comment]
I'll try that one, but in the meanwhile, I understood what is happening. So, basically during stepOver, the debugger keeps sending exec-until to the next line, but when the next line is actually the header of a new paragraph, GDB ignores this command the releases the execution.

**Comment by brunopacheco1** [comment]
As I understand, when the COBOL source is converted to C, PERFORM verb is converted to a goto operator, which means the source lines are in the same stack level.

So, following that idea, the code on StepOver could be simplified just to call the command exec-next, as the gdb is handling it correctly. There's no need to find the next line in the source map or build an execution graph, unless you have an idea of making `PERFORM ` to act as a function call (as I had before digging into this issue).

**Comment by OlegKunitsyn** [comment]
Released
