### ISSUE TITLE
Windows/Mac version

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#2]
Do you plan on supporting only gdb or also builds of GnuCOBOL that were created with cl.exe or Clang? I've read that both could be supported if you use lldb, possibly even the shared object files that you'd normally debug with gdb.

**Comment by brunopacheco1** [comment]
I've tried running it on Mac and that was the error I got.

cobc (GnuCOBOL) 2.2.0
Built     Oct 15 2019 14:14:21
Packaged  Sep 06 2017 18:48:43 UTC
C version "4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)"

GNU gdb (GDB) 9.1

![image](https://user-images.githubusercontent.com/4491850/80112758-c0320380-8581-11ea-8947-fd8d20d522e6.png)

**Comment by OlegKunitsyn** [comment]
> Do you plan on supporting only gdb or also builds of GnuCOBOL that were created with cl.exe or Clang? I've read that both could be supported if you use lldb, possibly even the shared object files that you'd normally debug with gdb.

No concrete plans, I believe in community. Feel free to add Mac/Win support via pull request.

**Comment by GitMensch** [comment]
> No concrete plans, I believe in community. Feel free to add Mac/Win support via pull request.

I suggest to keep the issue open (assigning a label like "needs pull request" if you like to, or adjusting the title) in this case.
