### ISSUE TITLE
StepOver goes into a CALL verb execution

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#21]
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
cobc (GnuCOBOL) 3.1-dev.0
[code](https://github.com/OlegKunitsyn/gnucobol-debug/blob/master/test/resources/sample.cbl)
[sample_verbose_log.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4563063/sample_verbose_log.txt)

It looks like the changes to fix #17 have introduced a bug on CALL verbs, I believe this verb is a real function call, so the assumption is that StepOver should execute internal instructions and keep in the same stack level, but now it is acting like StepInto.

**Comment by brunopacheco1** [comment]
Reading the log it looks like the GDB emits an "end-stepping-range" event, and in the mi2.ts there's a handler for that executing `stepInto()`. Is that correct? Perhaps it should be stepOver? In the afternoon I'll try to find some time to investigate more.

**Comment by brunopacheco1** [comment]
I was trying out changing this "end-stepping-range" event handler to `stepOver()` but then when it's needed to execute `stepInto()`, the action is ignored and a `stepOver()` runs.

**Comment by OlegKunitsyn** [comment]
Released. Thank you!

**Comment by GitMensch** [comment]
Hm, tested with the current extension and GnuCOBOL 3.1 - step over for `CALL` works fine, but step into doesn't. @brunopacheco1 can you have a look at this please? Do you have a working setup for a multi-program application (ideally compiled completely separate)?
