### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by OlegKunitsyn** [OlegKunitsyn/gnucobol-debug#23]
Gentlemen, I need a compiling ninja to produce `lcov.info`. Any ideas how?
```
$ cobc -x -A "-fprofile-arcs -ftest-coverage" -v -j hello.cbl

cobc (GnuCOBOL) 2.2.0
Built     Jul 17 2018 20:29:40  Packaged  Sep 06 2017 18:48:43 UTC
C version "8.1.0"
loading standard configuration file 'default.conf'
command line:   cobc -x -A -fprofile-arcs -ftest-coverage -v -j hello.cbl 
preprocessing:  hello.cbl -> /tmp/cob4801_0.cob
return status:  0
parsing:        /tmp/cob4801_0.cob (hello.cbl)
return status:  0
translating:    /tmp/cob4801_0.cob -> /tmp/cob4801_0.c (hello.cbl)
executing:      gcc -c -Wno-unused -fsigned-char -Wno-pointer-sign -Wdate-time
                -finline-functions -U_FORTIFY_SOURCE -pipe -fprofile-arcs
                -ftest-coverage -o "/tmp/cob4801_0.o" "/tmp/cob4801_0.c"
return status:  0
executing:      gcc -Wl,--export-dynamic -o "hello" "/tmp/cob4801_0.o"
                -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions
                -Wl,-z,relro -L/usr/lib/x86_64-linux-gnu -lcob -lm -lgmp
                -lncursesw -ldb-5.3 -ldl
/usr/bin/ld: /tmp/cob4801_0.o: in function `_GLOBAL__sub_I_00100_0_main':
cob4801_0.c:(.text+0x4f5): undefined reference to `__gcov_init'
/usr/bin/ld: /tmp/cob4801_0.o: in function `_GLOBAL__sub_D_00100_1_main':
cob4801_0.c:(.text+0x504): undefined reference to `__gcov_exit'
/usr/bin/ld: /tmp/cob4801_0.o:(.data.rel+0x20): undefined reference to `__gcov_merge_add'
collect2: error: ld returned 1 exit status
return status:  256 
```

**Comment by GitMensch** [comment]
As you see the compile and linking steps are separate here - I'd try to pass the coverage arguments with both `-A` and `-Q`.

**Comment by GitMensch** [comment]
Suggestion @OlegKunitsyn adjust the README

* add a note for additional requirements when using coverage
* possibly: have two launch.json defined, one with and one without coverage

**Comment by GitMensch** [comment]
@OlegKunitsyn Can you please exclude the `DATA DIVISION` from the coverage (multiple pages in RED just look very bad)?

**Comment by OlegKunitsyn** [comment]
> multiple pages in RED

Where? I see coverage in `PROCEDURE DIVISION` only

**Comment by GitMensch** [comment]
![coverage](https://user-images.githubusercontent.com/6699539/87118730-6554a200-c27c-11ea-838d-f663f9890cda.png)

**Comment by GitMensch** [comment]
@OlegKunitsyn can we please have the coverage function "detached" from the debugging function?
Reasons:

* showing coverage for a run that was not done "locally" with the same source or was not run "under control of vscodium" (for example a batch job) is currently not possible
* coverage should not be integrated into gdb.ts/mi2.ts as this makes the lldb support (#50) harder; it should be a "post step" that one may use (just add an extension command for showing the coverage) or a "special" launch configuration

What do you think?
