### ISSUE TITLE
"Could not start the debugger process" if cobc "says" something

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#25]
To reproduce: use anything that "works" (compilation + debugging until the first breakpoint). Then add `-v` to cobcargs in launch.json. Result:

The expected output from cobc is found in the debug console and is intermixed with a lot of "Could not start the debugger process" messages.

**Comment by GitMensch** [comment]
I just have seen that the perl debugger had the same issue https://github.com/raix/vscode-perl-debug/issues/52. It looks like they've changed the input/output handling to fix this (but I don't find the actual place in the referenced code changes as there were multiple changes mixed into one commit), maybe someone understanding what this code does could apply something similar for this extension.

**Comment by OlegKunitsyn** [comment]
Fixed in 0.22.14. Please confirm.

**Comment by GitMensch** [comment]
The part "if cobc says something but compiles fine the debugger doesn't start" is fixed now. But I find it really strange to don't see what the compiler says - especially when it tells why the debugging will never be able to start (compilation error).

**Comment by OlegKunitsyn** [comment]
Please try `"verbose":true`to see the output.

**Comment by GitMensch** [comment]
@OlegKunitsyn What do you think of automatically re-run with verbose:true if the return code of cobc shows an error?
In this case the default will still be silent but compilation errors will actually be shown.

**Comment by OlegKunitsyn** [comment]
> @OlegKunitsyn What do you think of automatically re-run with verbose:true if the return code of cobc shows an error?
> In this case the default will still be silent but compilation errors will actually be shown.

Errors, as well as Info and Warnings should use appropriate vscode API `vscode.window.show...`. Silent activity is perceived as a Rebellion of the machines, a loss of control.

**Comment by GitMensch** [comment]
Looks like we're speaking the same language now - so can you please ensure that cobc`s stderr which includes warnings and errors are forwarded to úse the appropriate vscode API?
