### ISSUE TITLE
fail to launch COBOL debugger

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#29]
The only output that is produced (even with verbose: true) is an error message

> Cannot read property 'toString' of null

Environment:
COBOL-Debugger 0.31.16
VSCodium 1.44.1
Windows_NT x64
GNU gdb (GDB) 7.6.1
cobc (GnuCOBOL) 3.1-dev (2020)
gcc (MinGW.org GCC-6.3.0-1) 6.3.0

**Comment by brunopacheco1** [comment]
Hi @GitMensch , could you share the COBOL source code or the `.c.l.h` source file of your tests?

**Comment by OlegKunitsyn** [comment]
It happens in case of failed shell-command. Just added an error escalation.

**Comment by OlegKunitsyn** [comment]
> Windows_NT x64

Please check this once again.

**Comment by GitMensch** [comment]
rechecked that environment, now says (with verbose option on)

> getThreads

in the debug console - nothing else.

**Comment by GitMensch** [comment]
ping @OlegKunitsyn having an error message in general (not only if manually set to verbose up-front) and to have an understandable error message would be ... useful.

**Comment by OlegKunitsyn** [comment]
Please check v2.31.28 once again. By the way, `ovsx publish` still forbids GitHub SVG status badges.

**Comment by GitMensch** [comment]
> By the way, `ovsx publish` still forbids GitHub SVG status badges.

According to https://github.com/eclipse/openvsx/issues/156 this is solved - as long as you updated osvx before, did you do that?

**Comment by GitMensch** [comment]
> Please check v2.31.28 once again.

Hm, I have no clue where this was, May was months ago...
So I've used something that seemed similar: Arnold's 3.1rc1 MinGW package - that's the exact same GDB and GCC version.

Created the environment (double-click on its contained set_env.cmd), made sure that all VSCodium instances were closed and started a new one from the cmd that was left open. Found one old workspace on the disk, started debugging there. First result: got a message "Failed to start MI Debugger" and a "file not found message" for the created executable.
Checked: the launch.json had no path set, and therefore the original file was used by cobc and the output stored in the current folder, which seems to default to the workspace root.
Deleted launch.json to start new, auto-generated the new one (no cwd set -> workspaceRoot -> likely correct), and pressed debug. Again - nothing happens, including no message in the debugging-console, terminal, output, problems.
After remembering that the (for me strange) default includes `-free`), I've commented that out and tried again.

Now I get the same error message as above:

~~~
Failed to load MI Debugger: /d/dev/gnucobol-debug-test/datatypes.exe: No such file or directory. (from file-exec-and-symbols "/d/dev/gnucobol-debug-test/datatypes.exe")
~~~

And the debugging console has

> Warning: /d/dev/gnucobol-debug-test: No such file or directory.

next run with `"verbose": true` shows the issue:

The extension says:
```
stdin: 4-environment-directory "/d/dev/gnucobol-debug-test"
stdin: 5-file-exec-and-symbols "/d/dev/gnucobol-debug-test/datatypes.exe"
```

And GDB says:

```
Warning: /d/dev/gnucobol-debug-test: No such file or directory.
stdout: 5^error,msg="/d/dev/gnucobol-debug-test/datatypes.exe: No such file or directory."
(gdb) 
```

I guess that path is set bad? Tried the following on the vscode terminal:

```
gdb
file "d:/dev/gnucobol-debug-test/datatypes.exe"
set environment-directory "d:/dev/gnucobol-debug-test"
run
```

worked fine - so the issue here seems to be the converted path "/d/dev" instead of "d:/dev".

I know I repeat myself with bringing on #24 and #26 - but a failing start in the first place (because of the cobc error rooting in `-free` that was not appropriate for the sample) **without any message at all** is at least as bad as the wrong path conversion.

**Comment by l-github-245** [comment]
Hi, would you know whether there is a workaround for this problem ? I am also using gnucobol 3.1rc1 on windows 10 and I am experiencing the same issue ..... Failed to load MI Debugger......

The software being used is bitlang.cobol (6.10.18) and your debugger (2.31.30). VS Code is 1.51.1 under win 10. gdb is 7.6.1 and gcc is 6.3.0

Do you need any extra info about the bug ? Let me know

**Comment by GitMensch** [comment]
I've outlined the workaround in the post directly before yours...

**Comment by OlegKunitsyn** [comment]
@l-github-245 thank you for your feedback. Unfortunately, can't maintain native GnuCOBOL setups on Windows 10. Please try Docker on Windows (fixed since #89) or contribute your fix.

**Comment by GitMensch** [comment]
> Unfortunately, can't maintain native GnuCOBOL setups on Windows 10.

No need to do much as the binaries are already provided officially by Arnold Trembley (likely very soon via GNU FTP-servers, too).
The most important thing to fix is the path that is provided to GDB as outlined above:
Extension sets: `/d/dev/gnucobol-debug-test` but should set `d:/dev/gnucobol-debug-test/datatypes.exe` (so the file and environment directory need an adjustment).

**Comment by l-github-245** [comment]
Yes, the setup is Trembley's binaries and no docker.

In my case, I got around this win32 path problem by removing some path conversions in mi2.js and parser.c.js. In nativePath, the line nat.replace....... under the process.platform === "win32" check was commented out and that did the trick. 

Not sure if this approach is legit though. In mi2.js, there is a check for the docker and if so it converts the path using nativePath.resolve .

While I can now debug gnucobol in win10, there still is some kind of a problem with 'Redirection is not supported' and some SCREEN SECTION setups, apparently a known issue (?). Remote debugging seems to be the solution but it does not seem to sense breakpoints. Would you have any pointers ?

**Comment by GitMensch** [comment]
Remote debugging is one option, but I'm not sure if this plugin already handles that. Attach to pid should work fine.
Other than that you could change the pdcurses.dll in Arnold's package by one build the same way (that's even possible with using Arnold's package) and use PDCursesMod wingui port. That way the application opens a separate window for screenio.

@l-github-245: as noted obove a path conversion is ok, as long as it is done as noted above. Can you please try to come up with a PR that checks for win32 and either use what is done currently (in "docker"-mode) or an adjusted one? This would really help a lot of users with the MinGW32-package from Arnold (and I guess the MSYS2 based packages, too).

**Comment by OlegKunitsyn** [comment]
@l-github-245 feel free to hack and create pull request: https://github.com/OlegKunitsyn/gnucobol-debug#development

**Comment by l-github-245** [comment]
Hi, I created a pull request with a possible fix. It works here with my win10 and Trembley's packages.

How does the validation process works now ? Could someone validate the fix in win10 native, with the docker and in linux ? 

Not yet got around to address my screen section woes and PDCurses. When I have time, I will check again. Arnold Trembley released a new package v3.1.1 with PDCursesMod v4.2.0 so maybe it will work for me this time.

**Comment by OlegKunitsyn** [comment]
@l-github-245 I've contacted Aaron.

**Comment by OlegKunitsyn** [comment]
@l-github-245 your PR released under v2.31.31.

**Comment by GitMensch** [comment]
"Works" as described in https://github.com/OlegKunitsyn/gnucobol-debug/issues/96#issuecomment-744042980,

**Comment by GitMensch** [comment]
Readme still has

> The extension has an in-progress Issue #29 accessing native Windows and mixed Docker-Windows paths. Your help would be greatly appreciated.

@OlegKunitsyn should we just remove that part?

**Comment by GitMensch** [comment]
README entry was removed with a200f0b6081b224b6e6eaecb3f989f485ed32240 so we can close that.
