### ISSUE TITLE
Error parsing COBOL file on Windows 7

### ISSUE THREAD

**Issue by tshifhiwao** [OlegKunitsyn/gnucobol-debug#32]
I installed the debugger and tried using it but i keep getting the same error error below,

`WARNING: Utility Command Server: Error in command socket Error: listen EACCES: permission denied C:\Users\********\AppData\Local\Temp\gnucobol-debug-sockets\debug-instance-cotk
WARNING: The examine memory location command won't work
[New Thread 54236.0xc6e4]`

how to fix this?

**Comment by brunopacheco1** [comment]
@tshifhiwao Thanks for your feedback. Could you describe your configuration? OS, GDB, GNUCobol and VSCode versions, if you are running locally or running over docker/WSL/WSL2.

**Comment by tshifhiwao** [comment]
I am running on windows 7 locally, the GDB i installed is the one found on VSCodium called GDB Debug by DamianKoper, 


`cobc --version
cobc (GnuCOBOL) 3.1-dev.0
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Keisuke Nishida, Roger While, Ron Norman, Simon Sobisch, Edward Hart
Built     Mar 24 2020 19:58:23
Packaged  Mar 22 2020 20:37:48 UTC
C version (MinGW) "6.3.0"`


my launch.json file is like this 

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "program":"{$workspaceRoot}",
            "target": "${file}",
            "targetargs": [],
            "cwd": "${workspaceRoot}",
            "env": { "COB_CFLAGS" :"-ggdb" },
            "gdbpath": "gdb",
            "cobcpath": "cobc",
            "cobcargs": ["-x"],
            "group": [],
            "coverage": false
        }
    ]
}`

**Comment by brunopacheco1** [comment]
Any particular reason to set `COB_CFLAGS`? It's not advisable doing that, you should either use cobargs `-A` or set the env variable COB_LDFLAGS to add extra args to the C compiler.

**Comment by brunopacheco1** [comment]
This GDB Debug by DamianKoper is another debugger extension for VSCode, but you should have a GDB installed locally as well. Could you share its version?

**Comment by tshifhiwao** [comment]
There is no particular reason, i actually added that today earlier on, it didn't make any difference. Unfortunately that's the only debugger i have.
[log.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4656142/log.txt)

**Comment by brunopacheco1** [comment]
Could you run `gdb --version` on your terminal and share what you've got?

This warning seems to be Windows blocking GDB to have privileged access. By the log file you just shared, this is a warning and it didn't block the debugger to run. Were you able to debug and stepover on your code?

**Comment by tshifhiwao** [comment]
I just noticed now, the GnuCOBOL that i have installed came with gdb, i downloaded it from Arnold website.

gdb --version
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.

**Comment by tshifhiwao** [comment]
No i can not debug or step over, i get this error "malformed linespec error: unexpected colon"

the first log i had removed the breakpoints

The log i am attaching now has two breakpoints, notice the the error.
[log.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4656251/log.txt)

**Comment by tshifhiwao** [comment]
Here is the screenshot after i try to compile.

![error screenshot](https://user-images.githubusercontent.com/65654760/82437660-123e4a00-9a98-11ea-82d9-81730e143820.png)

**Comment by brunopacheco1** [comment]
Great, thanks for your details. So, the warnings presented at the beginning of the logs look harmless so far.

And about "malformed linespec error: unexpected colon" seems to come from the lines just write after `SourceMap created: lines 7, vars 6`. 

Actual parsing:
`undefined 8 > C:\Users\UserName\Downloads\cobjapi\SWING\examples_simple\test.c 95`
Expected parsing:
`c:\Users\UserName\Downloads\cobjapi\SWING\examples_simple\test.cbl 999 > C:\Users\UserName\Downloads\cobjapi\SWING\examples_simple\test.c 95` where 999 is just a fake value, just to exemplify.

So the parsing is not happening properly on Windows (which is not a fully supported platform yet, only via WSL and docker).

**Comment by brunopacheco1** [comment]
Could you rename this issue to something related to this parsing COBOL file on Windows?

It would be really nice if you could clone the extension and debug it locally, and perhaps commit the fix. Let me know if you need some support on that if you want to dig on it.

**Comment by tshifhiwao** [comment]
I have never done it before but i would try if you show me the way. :+1:

**Comment by OlegKunitsyn** [comment]
> Here is the screenshot after i try to compile.

Windows is not supported yet. Actually, you may clone and debug the extension by setting the breakpoints in TS here and there :)  
If you let me know a step-by-step installation of cobc+gdb on win7 I would test that afterhours.

**Comment by brunopacheco1** [comment]
So let's try then.

* Click on "Fork", on the top of this repo page. This will create a copy of this repo to you github account.
* Now you clone your copied repo to your machine and open it on VSCode.
* On VSCode, you press F5 to execute the extension locally. This will open a new VSCode window, with the local extension running.
* On this second VSCode window, you open your COBOL code and start debugging it.
* On the first VSCode you can insert breakpoints wherever you think is needed in order to debug the extension code.

The [parser.c.ts](https://github.com/OlegKunitsyn/gnucobol-debug/blob/master/src/parser.c.ts) is the class responsible for parsing the cobol file, you can start debugging it.

**Comment by brunopacheco1** [comment]
Please, let me know if you are going to tackle it, otherwise, I can take a look at it later tonight.

**Comment by tshifhiwao** [comment]
> If you let me know a step-by-step installation of cobc+gdb on win7 I would test that afterhours.

I downloaded the [GnuCOBOL Binary from Arnold ](https://www.arnoldtrembley.com/GC31-r3577-G-BDB-rename-7z-to-exe.7z)

1. Created a fold "C:\GnuCOBOL" and extracted the binary into that folder
2. set the environment variables like this,
|-------------------------------------------------------|
|Variable	                                  |value                      |
|-------------------------------------------------------|
|COB_CONFIG_DIR	             |/GnuCOBOL/config           |
|-------------------------------------------------------|
|COB_COPY_DIR	            |/GnuCOBOL/copy             |
|-------------------------------------------------------|
|COB_INCLUDE_PATH	        |/GnuCOBOL/include          |
|-------------------------------------------------------|
|COB_LIB_PATH	            |/GnuCOBOL/lib              |
|-------------------------------------------------------|
|PATH	                    |/GnuCOBOL/bin              |
|-------------------------------------------------------|


My Launch.json file 

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "COBOL debugger",
            "type": "gdb",
            "request": "launch",
            "target": "${file}",
            "targetargs": [],
            "cwd": "${workspaceRoot}",
            "gdbpath": "C:/GnuCOBOL/bin/gdb.exe",
            "cobcpath": "cobc",
            "cobcargs": ["-x"],
            "group": [],
            "coverage":true,
            "verbose": true
        }
    ]
}

**Comment by tshifhiwao** [comment]
> Please, let me know if you are going to tackle it, otherwise, I can take a look at it later tonight.

If it's possible for you to do it tonight, please go ahead as i will take forever.

**Comment by GitMensch** [comment]
Just a hint - it is *much* easier and error prone to not set any variables, instead:

1 download and unpack the package from Arnold's site (that are since some years the *official* MinGW packages for GnuCOBOL!)
2 open cmd.exe
3 execute the following commands
```cmd
pushd W:\here\ever\unpacked\to
set_env.cmd
vscodium.exe
```
you may just drop the folder instead of type the name for the first command and may use vscode (you can install VSCodium along to VSCode and while I think you currently won't move it is still a good idea to have them installed at least along) and/or the absolute path to the binary.

**Comment by OlegKunitsyn** [comment]
Fixed Windows paths in 0.31.18. Please check this out.

**Comment by tshifhiwao** [comment]
Thank you, now it works on both VSCodium and VSCode. :)
