### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#33]
The [Open VSX Registry](https://github.com/eclipse/openvsx) has only one [COBOL extension](http://open-vsx.org/?search=cobol) yet. This one should definitely be added.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by OlegKunitsyn** [comment]
Done. Thanks for advice!

**Comment by GitMensch** [comment]
Thank you very much for http://open-vsx.org/extension/OlegKunitsyn/gnucobol-debug, as the openvsx registry will be the default "marketplace" URL used in VSCodium on the next release, this extension will be found there by default, too.

_Hint: the side above mentions that you may want to "claim ownership" of OlegKunitsyn._
