### ISSUE TITLE
Can not watch a record inside a group as it produce error "TypeError: Cannot read property 'cName' of undefined"

### ISSUE THREAD

**Issue by tshifhiwao** [OlegKunitsyn/gnucobol-debug#35]
If you watch a level 01 record everything works fine.

If you add any record that is part of a group, you get this error  "TypeError: Cannot read property 'cName' of undefined"

A Sample program
```cobol
          IDENTIFICATION DIVISION.
            PROGRAM-ID. test.
            ENVIRONMENT DIVISION. 
            DATA DIVISION.        
            WORKING-STORAGE SECTION.
            01  WS-A.
                05  WS-AA                           PIC X(8).
                05  WS-AB                           PIC X(8).
                05  WS-AC                           PIC 9(8).
                05  WS-AD                           PIC 9(8).
            01  WS-B.
                05 WS-BA                            PIC X(8).
                05 WS-BB                            PIC X(8). 
            
            PROCEDURE DIVISION.
            
            MAINFILE.
                MOVE "ABC12345" TO WS-AA.
                MOVE WS-AA      TO WS-AB.
                MOVE 12345678   TO WS-AC.
                MOVE WS-AC      TO WS-AD.

                MOVE WS-AA TO WS-BA
                STOP RUN.
```

Testing on windows 7 

cobc -version
cobc (GnuCOBOL) 3.1-dev.0
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Keisuke Nishida, Roger While, Ron Norman, Simon Sobisch, Edward Hart
Built     May 17 2020 18:04:31
Packaged  May 16 2020 23:06:42 UTC
C version (MinGW) "6.3.0"

gdb version
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
version: No such file or directory.
(gdb)

I am testing using the compiler built by Arnold.

![error screenshot](https://user-images.githubusercontent.com/65654760/82539532-e087ba80-9b4d-11ea-8ea6-08e01c7d18b3.png)

**Comment by brunopacheco1** [comment]
Thanks @tshifhiwao for your report.

So, gnucobol compiler does a parsing from COBOL to C and from C it compiles to the executable. During this process, the variables may be ignored if they are not used during runtime, which seems to be the case of this WS-TEST.

Try adding a new instruction like `DISPLAY WS-TEST.`, you will see that this variable is going to be presented in the variable panel and it is going to be possible to watch it.

**Comment by brunopacheco1** [comment]
BTW, there's an option on gnucobol 3.1+ (`-fdump=ALL`) that dumps more variables into C code, but it still not guaranteed that all variables typed down on WORKING-STORAGE SECTION are going to be fully represented on C and consequently observable from the variable panel.

**Comment by brunopacheco1** [comment]
@OlegKunitsyn What do you think showing a better message when a variable is not found? We may need an expression parser as this WATCH panel can contain a real expression (`WS-AA + WS-AB`), not only variable names.

**Comment by brunopacheco1** [comment]
@tshifhiwao  Another remark, if you want to watch a variable inside a group, you have to type the full path in order to see its value, for instance `WS-A.WS-AA`, instead of `WS-AA`.

@OlegKunitsyn Do you think this is the correct behavior or we should try to find the variable anyway, no matter the hierarchy?

**Comment by OlegKunitsyn** [comment]
> What do you think showing a better message when a variable is not found? We may need an expression parser as this WATCH panel can contain a real expression (`WS-AA + WS-AB`), not only variable names.

"Not found" or empty? In beta, we may try anything.

> Do you think this is the correct behavior or we should try to find the variable anyway, no matter the hierarchy?

Thank you for your contribution! Keep it simple, enjoy the weekend and believe in crowdsourcing. :)

**Comment by GitMensch** [comment]
> 
> 
> BTW, there's an option on gnucobol 3.1+ (`-fdump=ALL`) that dumps more variables into C code, but it is still not a guarantee that all variables typed down on WORKING-STORAGE SECTION are going to be fully represented on C and consequently observable from the variable panel.

Can you please elaborate on this @brunopacheco1? They should be represented (with the exclusion of the special handled `OCCURS` items for now).

> What do you think showing a better message when a variable is not found?

I'd go with "variable '%s' unknown".

> [...] you have to type the full path in order to see its value [...] Do you think this is the correct behavior or we should try to find the variable anyway, no matter the hierarchy?

It would be good to keep it the COBOL way here - if the variable doesn't need any qualification then `WS-AA` should work, otherwise a warning message should appear that qualification is needed, something like "variable '%s' needs qualification".
Ideally _additional_ the COBOL way of qualification works, too:
`WS-AA IN WS-A` / `WS-AA OF WS-A`

and also the COBOL qualification - in the case of `WS-A.WS-D.WS-AA` and `WS-B.WS-E.WS-AA` one may use `WS-AA IN WS-D IN WS-A` / `WS-AA IN WS-D` / `WS-AA IN WS-A`. If this is more work I suggest to track this in a separate issue for later (this way we say "it is known" and either "patches welcome" or "planned to be done").

> We may need an expression parser as this WATCH panel can contain a real expression (`WS-AA + WS-AB`), not only variable names.

Supporting expressions would be **really cool**. Note: this is also related to #38 and #39.

**Comment by brunopacheco1** [comment]
> Can you please elaborate on this @brunopacheco1? They should be represented (with the exclusion of the special handled `OCCURS` items for now).

What I meant here was if the field is listed on `*.c.l.h`, the extension is going to show it on the Variables Panel, once it is part of the current function scope during debugging mode.

In some cases, like in the sample provided by @tshifhiwao ,  some fields are not compiled into the  `*.c.l.h`, as it is never explicitly used during runtime.

**Comment by brunopacheco1** [comment]
I pushed a fix to present 'not available' when the variable is not found. This message is the same presented by VSCode by default when the debugging mode is not running. 

I changed also the way we are looking for variables. Relative paths are now accepted, to avoid confusion. So, W`S-A.WS-AA` and `WS-AA` should return the same variable.

**Comment by tshifhiwao** [comment]
The fix is not yet in the VS Code Marketplace

**Comment by OlegKunitsyn** [comment]
> Thank you @brunopacheco1 but the fix is not yet in the VS Code Marketplace, the current version is still 0.31.18

0.31.19 released. Please check.

**Comment by GitMensch** [comment]
@OlegKunitsyn please tag the released version, too - the last one is 0.31.18. thx

**Comment by tshifhiwao** [comment]
The debugger is broken, it doesn't show local variables anymore, watch is not working even hover doesn't work. 

`{
    "version": "0.2.0",
    "configurations": [                                                                    
        {                                                                                  
            "name": "COBOL debugger",                                                      
            "type": "gdb",                                                                 
            "request": "launch",                                                           
            "target": "${file}",                                                           
            "targetargs": [],                                                              
            "cwd": "${workspaceRoot}",                                                     
            "gdbpath": "gdb",                                                              
            "cobcpath": "cobc",                                                            
            "cobcargs": ["-x"],                                                            
            "group": [],                                                                   
            "coverage":true,                                                               
            "verbose": true                                                                
        }                                                                                  
    ]                                                                                      
}                                                                                          
[VERBOSE.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4728149/VERBOSE.txt)
`


![Untitled](https://user-images.githubusercontent.com/65654760/83725908-04192d80-a643-11ea-8a7e-e72e9246c868.png)

**Comment by tshifhiwao** [comment]
[VERBOSE.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4728210/VERBOSE.txt)

**Comment by brunopacheco1** [comment]
Interesting, how is it possible for STDOUT not being there?

@tshifhiwao Thanks a lot for your reports. We'll investigate this issue.

**Comment by GitMensch** [comment]
> Interesting, how is it possible for STDOUT not being there?

What do you mean by that?

**Comment by brunopacheco1** [comment]
Checking the log file and the printscreen, the failure is happening on `call (void)fprintf(stdout,"18^done,value=|")`. GDB couldn't find `stdout`, so it couldn't print the custom MI event and by that the extension couldn't get the variables' values.

**Comment by brunopacheco1** [comment]
But I assumed that `stdout` scope was global.

**Comment by GitMensch** [comment]
> But I assumed that `stdout` scope was global.

I've assumed similar in the past, too :-)
While there can be multiple things that interfere the most important part is that different C runtimes have different (access) to handles (this also applies to file and stream handles, environment and memory).
If you get or pass an explicit file handle everything is fine, but if you just access them from the C runtime you may get something other than you expect. This happens especially often in Win32 (there are systems with multiple libc versions where binaries interact over those "borders", but that's nothing compared to the myriad of C runtimes in Win32).

This is one of the reasons that it would be reasonable to do `cobcrun --info` once in verbose mode, at least showing it; or even better `call (void)print_info(void)` once and output the information.

... but I have no clue why GDB cannot find stdout at all. Is it `null`, is it "something" GDB uses but does not "see" the result, ???
Hm. I did not spot where GDB actually used comes from in the VERBOSE.txt, can you add this piece of information? The COBOL part comes all from `C:\\GnuCOBOL\\bin` and is from one of the packages from Arnold Trembley. @tshifhiwao Can you please drop a link which build you did use?

**Comment by tshifhiwao** [comment]
Hi Simon, the compiler i am using is this version on windows 7/10 [https://www.arnoldtrembley.com/GC31-r3577-G-BDB-rename-7z-to-exe.7z](https://www.arnoldtrembley.com/GC31-r3577-G-BDB-rename-7z-to-exe.7z)


There are two scenarios
scenario 1: if you open VSCodium and run debugger for the first time, the local variables will be available, when you expand them so that you can look at the values then the problem starts. Below is the screenshot and the verbose text file.
![TEST1](https://user-images.githubusercontent.com/65654760/83796578-86d0d580-a6a1-11ea-808f-1e8fa073067a.png)

[VERBOSE1.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4732044/VERBOSE1.txt)


Below is the `where gdb`  information and `cobcrun` information
[cobcrun.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4732048/cobcrun.txt)

**Comment by tshifhiwao** [comment]
scenario 2: After you run first attempt and stop the debugger then try to run the debugger again that's when you don't get the local variables anymore, in both scenarios, watch doesn't work. Below is the screenshot and verbose text file.

![TEST2](https://user-images.githubusercontent.com/65654760/83797170-7cfba200-a6a2-11ea-9cce-7ad5f2856204.png)

[VERBOSE2.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4732082/VERBOSE2.txt)

**Comment by brunopacheco1** [comment]
Well, at least the bug is consistent, after installing a Windows env, it happens to me.

**Comment by brunopacheco1** [comment]
As I was already suspecting, the problem was in the command `call (void)fprintf(stdout, "17^done,value=|")`, but fortunately the solution is quite simple, replacing it by `call (void)printf("17^done,value=|")` makes the whole thing working again, and it didn't break GC2.2/GC3.1-dev running on Linux or Docker.

**Comment by brunopacheco1** [comment]
BTW, the second scenario seems to be a side effect of the first, I couldn't reproduce it after the fix.

**Comment by brunopacheco1** [comment]
PS: @OlegKunitsyn It looks the extension is working properly on Windows after this fix and the last changes. What do you think?

**Comment by OlegKunitsyn** [comment]
> PS: @OlegKunitsyn It looks the extension is working properly on Windows after this fix and the last changes. What do you think?

Released. Thank you!

**Comment by tshifhiwao** [comment]
Everything is now working again including watch. In the future if it's possible to investigate this further, we should allow watch to work on all variables even if they don't have `DISPLAY`. @OlegKunitsyn @brunopacheco1 should i now close this bug because it is fixed and working?

**Comment by GitMensch** [comment]
Just rechecked after those changes, the variable list is complete for me but no variable can be shown at all. The first gets a wait signaled, when I then try to open the second one I get the beautiful

> Could not expand variable: TypeError: Cannot read property 'cName' of undefined

vscode: 1.44.1
os: win10
gc: ArnoldTrembley-build GC31-r3577-VB
