### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by OlegKunitsyn** [OlegKunitsyn/gnucobol-debug#37]
Opensource common libs that extend INTRINSIC of GnuCOBOL do not exist. The downloadable programs on SF and https://open-cobol.sourceforge.io/faq/index.html are cool but insufficient. 
`COPY "[vendor]/[package].cpy"` may include 3rd-party libs. Which Package manager do you prefer for GnuCOBOL?

**Comment by GitMensch** [comment]
I'm not sure what this is about but it seems to be better placed in the [GnuCOBOL discussion boards](https://sourceforge.net/p/open-cobol/discussion/). And in case you've missed it see the [GnuCOBOL contributions](https://sourceforge.net/p/open-cobol/contrib/HEAD/tree/trunk/), especially ESQL, the TUI tools and cobjapi are often used and still updated and the samples are nice, too.
