### ISSUE TITLE
support for expressions on WATCH panel

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#44]
The extension could support real expressions on WATCH panel, so the developer can have extra features and a richer experience when debugging.

![image](https://user-images.githubusercontent.com/4491850/83811471-2c903e80-a6ba-11ea-97d1-e14491519fb2.png)

**Comment by GitMensch** [comment]
That would be really useful, especially if you can use cob_fields here, too, for example `dbl * flt - 2`.
Is that a working prototype or only a mockup?

**Comment by brunopacheco1** [comment]
Yep, this is a partially working prototype, I was trying out some possibilities, like:
* Use the JavaScript in background to run the expression (the test you are seeing), so extension would replace the COBOL variables by the actual values as literals;
* Define one specific expression language only for this extension;

The first is quite tempting as we wouldn't have to code anything, just manipulate the expression string and run `eval(expression)`. We would have out of the box a well established and wide library. Expressions like these in theory should work: `Math.pow(RADIUS, 2) * PI` or `COMMENT.substring(0, 30)`. The issue with this solution is a lot of uncertainties and side effects around the input expressions.

The second approach sounds like we are reinventing the wheel, but from another point of view, is a safer choice, as we would gradually deliver new features to the expression evaluator (we can enforce a sintax).

**Comment by GitMensch** [comment]
If it isn't too much work I suggest to go with the first approach for now (which would also seem like a solution to @tshifhiwao's request at https://github.com/OlegKunitsyn/gnucobol-debug/issues/35#issuecomment-639291279) as an intermediate solution and tracking the second option as new issue, coming back to it when time permits. I *think* this may also be needed to have "real COBOL expressions" which we reference already in #38 and #39.
... I'm still longing for #3 (to be specific: attach to a process running on a different machine) as this is needed for me _personally_ to actually be able to use this extension).

**Comment by brunopacheco1** [comment]
The first approach shouldn't be expensive, but surprisingly I am struggling to define a regex for the identifiers. It looks like on GC 2.2 it's similar to C as an identifier cannot start with a number but on GC 3.1 this is not true and so far I didn't find anything on GC code, perhaps you can speed up this process if you know exactly the definition of an identifier in GC 2.2 and 3.1.

**Comment by brunopacheco1** [comment]
Hello folks. The expression parser in general looks good.

So far the only problem was related to JavaScript not recognizing some literals (e.g. `+03.00` as a number). I believe to fix this I'll need to get the correct numeric type from the cob attribute and call parseFloat whenever it is required to. 

![image](https://user-images.githubusercontent.com/4491850/83981669-4e8afa80-a920-11ea-8987-7f2b8dae10ff.png)

**Comment by GitMensch** [comment]
Hm, at least in the first version I'd leave the floating conversion out, when you have this you'd also take care of stuff like `displayNumeric + compNumeric + (3 * floatVal) - (doubleVal + 2) - comp5Numeric` - at least I'm not sure what stuff needs to be converted to let this work correctly.
... while floating-point numeric is relative uncommon in COBOL it may need to be internally supported for division support in the watch panel.

**Comment by GitMensch** [comment]
But now I'm eager to see those changes in a release :-)

**Comment by brunopacheco1** [comment]
Well, it looks like if we remove the starting zeroes from the numeric values, fixes the problem.

![image](https://user-images.githubusercontent.com/4491850/84206249-11a13e00-aaaf-11ea-8cf9-8c331caf240a.png)

**Comment by OlegKunitsyn** [comment]
![Screenshot from 2020-06-10 06-42-48](https://user-images.githubusercontent.com/2870028/84228183-a2dfd700-aae6-11ea-8c72-72e31ffa7a7f.png)

Variables representation is a bit different. Expected?

**Comment by GitMensch** [comment]
> Variables representation is a bit different. Expected?

Not from my point of view, actually the remove of trailing zeroes is something that @brunopacheco1 explicit had to add for the watch panel and it was something that is in his screenshots in this PR for longer.

I _guess_ that 63c7dabb954c58ecfa9b3bb83db7c0aed42c5c93 is to be blamed for the different display.

**Comment by OlegKunitsyn** [comment]
Alright, zeroes and group value were expected. But let me ask first. :)
As as user, I would like is to get the most information from the value: name, type, length and content.
Mathematically, content +000000000002 and 2 are identical but not the length. Can we have them both i.e.  `TOTAL-QUANTITY: Numeric 3` `Value: 9`?

**Comment by brunopacheco1** [comment]
It is possible. The cob attribute has this info and more.
I would suggest to tackle these changes in another issue and close this issue and the issue about printing Variable values (if that one is stable of course).
Sent from Yahoo Mail for iPhone


On Thursday, June 11, 2020, 6:53 AM, OlegKunitsyn <notifications@github.com> wrote:




Alright, zeroes and group value were expected. But let me ask first. :)
As as user, I would like is to get the most information from the value: name, type, length and content.
Mathematically, content +000000000002 and 2 are identical but not the length. Can we have them both i.e. TOTAL-QUANTITY: Numeric 3 Value: 9?

**Comment by GitMensch** [comment]
> As as user, I would like is to get the most information from the value: name, type, length and content.
> Mathematically, content +000000000002 and 2 are identical but not the length. Can we have them both i.e. `TOTAL-QUANTITY: Numeric 3` `Value: 9`?
> 
> Update: I mean length in chars provided by gdb e.g. https://github.com/OlegKunitsyn/gnucobol-debug/blob/5455f97dc424d9e1ac5205b0e17f25bc9444c069/screenshot.png

**Please don't change watch or variable view this way.**
If you want to add this information to the variable list then it should have the COBOL definition, not the C definition.
It _may_ sound reasonable to have the definition on hover.

In any case I'd argue that the COBOL definition is also available by different extensions with standard vscode functions: "go to definition" (and the possibly using "go last" to get back) and "peek definition", therefore I'd highly recommend to not add the definition in this debugging extension anywhere; if you want to add this: use the full COBOL definition and put it in the variable list.

... a completely different issue which would be much better but I have no idea how to implement it is to be able to switch between COBOL and C during debugging - that would be very useful and would also have the "C" definitions handled by the C debugger and variable list and much more.
