### ISSUE TITLE
Should we display cob field details on Variable Panel/Hover variable description?

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#48]
Dear fellows, I'm opening this issue to move the discussion and have a cleaner discussion thread.

So, the initial idea of @OlegKunitsyn was adding more details to the variable type. For instance today we display `Numeric`, `Alphanumeric` and so on, but we could present more details if possible.

The variables cob_attribute in C are a good candidate to extract that info, and they can help to specify more the variable types we currently display. Besides, there're some minor issues when display certain types, for example, Pointer is displayed as Numeric binary.

Examples:
- `Group` to `Group (${size})`
- `Numeric` to `Numeric (${signed},${digits}, ${scale})`
- `Alphanumeric` to `Alphanumeric (${size})`
- Fix `Alphabetic`, currently it's displayed as `Alphanumeric`, and attribute details
- Fix `Pointer`, currently it's displayed as `Numeric binary`, and attribute details

**Comment by brunopacheco1** [comment]
@GitMensch, do you thing this is a good approach? Is there a way in libcob to get more details from the cob_field?

**Comment by GitMensch** [comment]
> Do you thing this is a good approach?

This approach is reasonable.

> Is there a way in libcob to get more details from the cob_field?

Not any more than you already have in the attributes. Depending on "something" the attribute also has a reference to the picture, but this is often not included (would have to recheck if and on what compiler switches this changes).
The attributes already specify the usage as pointer and similar.

**Comment by brunopacheco1** [comment]
Please, let me know what do you think about the Variable Panel.

![image](https://user-images.githubusercontent.com/4491850/84448928-47c7f480-ac4c-11ea-9fd9-15bc940fa34e.png)

**Comment by brunopacheco1** [comment]
![image](https://user-images.githubusercontent.com/4491850/84449045-91184400-ac4c-11ea-9976-84c433c18dd9.png)

**Comment by brunopacheco1** [comment]
![image](https://user-images.githubusercontent.com/4491850/84449079-a2f9e700-ac4c-11ea-819c-86de1e0696b2.png)

**Comment by GitMensch** [comment]
> Please, let me know what you think about the Variable Panel.

I guess @OlegKunitsyn may like this, but I have to admit that I find it to show too much information:

* common variable names in the wild are often longer and if you have 18-30 characters in there the additional descriptions take too much space, but that's maybe someone will get used to. If we want to keep it a similar way I'd vote to make it all lower-case and use short identifiers with a COBOL background (Numeric xyz->xyz, for example "binary", "edited", ...)
* in general I'd not have a group show any value in that panel, only do so upon explicit request (by a `p`rint command or by hover)

Other than that: nice :-)

**Comment by OlegKunitsyn** [comment]
> Please, let me know what you think about the Variable Panel.
> 
> ![image](https://user-images.githubusercontent.com/4491850/84448928-47c7f480-ac4c-11ea-9fd9-15bc940fa34e.png)

Sexy.

**Comment by brunopacheco1** [comment]
I agree with @GitMensch , apart from being informative, it is quite polluted.

What would you say adding the attribute as a field in the variable tree, something like:
`{
    "num": {
        "type": "Numeric Binary",
        "attribute": { "signed": true, "digits": 30, "scale": 3 },
        "value": "Blablabla"
    }
}`
Or even:
`{
    "num": {
        "type": "Numeric Binary",
        "signed": true,
        "digits": 30,
        "scale": 3,
        "value": "Blablabla"
    }
}`

**Comment by GitMensch** [comment]
What do you mean with variable tree - the output found in the verbose debug console - and keeping the variable panel "clean"?

I'd be totally to do this!

... and to remove the output from the groups, I have groups with mulitple sub-groups here all having hundreds and thousands of bytes - which I'd like to see (in the variable pane) in the actual items, not every place above (to see group items with hover would be quite useful though)

**Comment by OlegKunitsyn** [comment]
> What would you say adding the attribute as a field in the variable tree, something like:
> `{ "num": { "type": "Numeric Binary", "attribute": { "signed": true, "digits": 30, "scale": 3 }, "value": "Blablabla" } }`
> Or even:
> `{ "num": { "type": "Numeric Binary", "signed": true, "digits": 30, "scale": 3, "value": "Blablabla" } }`

I like both :)

**Comment by GitMensch** [comment]
So the plan is to include it in the internal field, ideally setup only when necessary, correct? Hhow would that be viewed as "interested programmer that doesn't like the COBOL peek"?

Furthermore I guess the variable panel gets _some_ of this displayed?

Can we agree that the variable panel does not get a value displayed for items of type "Group"?

Side questions: Is there a reason to not go with all lower-case in the type attribute? Is there a reason to keep this a string instead of an enum?

**Comment by brunopacheco1** [comment]
This is what I meant:

![image](https://user-images.githubusercontent.com/4491850/84829244-b7145e80-b027-11ea-9eaa-467f9f84f3a4.png)

**Comment by brunopacheco1** [comment]
I agree to remove Group value, when there is no child, as in the sample above.
No specific reason for having the variable types like that, we can put all to lower case.
We just have to agree on how we should display these values, to finish this task.

**Comment by GitMensch** [comment]
> I agree to remove Group value

Sounds good.

> No specific reason for having the variable types like that, we can put all to lower case.

Sounds good, too.

> This is what I meant: ...
> We just have to agree on how we should display these values, to finish this task.

Maybe we can have a setting in the extension to only enable this much info upon explicit request or (I don't know if that's even possible) only when hovering over the variable pane (if this isn't the case: when hovering over the variable)?

The usefulness of the variable pane is that it allows for a quick overview over the current stack frames data, which isn't the case when it is full of "structural/attribute" information


BTW: Can I suggest to get rid of (or disable) the IBM extension? Or is there a specific reason to use it?

**Comment by OlegKunitsyn** [comment]
I prefer to see what I've declared: lowercase, uppercase, camelcase. Coding style is another topic. 

Yes, feel free to remove Group value without children.

I was using IBM extension from time to time, without compiler.

The extension not a GNU product and must must not limit the programmers. Upcoming Package Manager will support the dialects including gnucobol and entcobol.

Keep the door open, gentlemen. :)

**Comment by GitMensch** [comment]
> I prefer to see what I've declared: lowercase, uppercase, camelcase.

I totally agree here, the identifiers should ideally be as they where defined - and actually this is the way it is included in the field storage comments and as literals in the dump code.

My request for "all lower-case" was about the type specifier (like: group, integer, numeric).

> The extension is not a GNU product and must not limit the programmers. Upcoming Package Manager will support the dialects including gnucobol and entcobol.

I totally agree here, too - but the debugger depends something like 98% on the C based generation of modules in a way GnuCOBOL does and also has it in its name.
Instead of the IBM extension I suggest to use bitlang.cobol which works also fine in "IBM" mode.

**Comment by brunopacheco1** [comment]
@OlegKunitsyn What would you say adding a launch configuration to enable the attribute details in the variable panel?

**Comment by GitMensch** [comment]
That sounds like a possible implementation, but why not have this globally in the extension settings instead? I'm aware that this extension has no settings yet but I'm sure we'd need them at some time in any case.

**Comment by brunopacheco1** [comment]
I am not sure how to do it right away, but either way is okay for me.

**Comment by OlegKunitsyn** [comment]
Please keep it simple and enable by default. AFAIK @GitMensch is not a user of the extension. 
No one complains :)

**Comment by OlegKunitsyn** [comment]
> I totally agree here, too - but the debugger depends something like 98% on the C based generation of modules in a way GnuCOBOL does and also has it in its name.
> Instead of the IBM extension I suggest to use bitlang.cobol which works also fine in "IBM" mode.

"gnu" keyword is not problem. I would integrate any other free (redistributable) dialect and replace C hell with predictable debugging API. Independence from FSF not a bad thing.

**Comment by GitMensch** [comment]
> Please keep it simple and enable by default.

Using extension settings is something which is simple for the user and 

> AFAIK @GitMensch is not a user of the extension.

I _think_ you mean "not someone that contributed by code so far"? How should I had all those issues created without using it (via VSCodium as apt install on Trisquel and on a Win32 machine using Arnold's builds, the Win32 environment breaks more often than it is usable [currently]).
I also consider other ways than "contributing code" still a contribution, but it is possible that I'm considering it more important for this project that it actually is.

> No one complains :)

The new variable panel with more "to the COBOL-programmer's view 'noise'" isn't released so far. I try to ensure that "users" don't need to complain.
I totally understand that it it useful for some people, especially for the ones that contribute to this extension by code, I'm just very sure that it is useful with showing more actual fields and less "structural info that is in the code" for someone that has to debug a program with a lot of variables.

But again: my COBOL debugging experience has not reached two decades yet and also doesn't extend more than 6 debugging frontends, so this is still a limited personal opinion.

**Comment by OlegKunitsyn** [comment]
Just to be clear. I highly appreciate each line of code and each comment contributed to the project. Furthermore, contribution in the form of ideas/bugreports is more important than coding. Unfortunately, those 750 installs have not led to the expression of opinions of *end* users yet.

>I'm still longing for #3 (to be specific: attach to a process running on a different machine) as this is needed for me personally to actually be able to use this extension).

I can't say I'm a user writing COBOL code for fun. Therefore, I conclude, that any *our* decision is good enough. At the moment here is no voice of real user to hear from.

@brunopacheco1 feel free!

**Comment by GitMensch** [comment]
I'd say that issue is now closed by the merge of #52 (haven't tested it yet, but assume it works).

**Comment by OlegKunitsyn** [comment]
@brunopacheco1 since v.0.31.19 debug console displays the log in `verbose=false` mode e.g.
```
call (void)printf("18^done,value=|")
call (void)cob_display(0,1,1,&f_14)
call (void)printf("19^done,value=|")
call (void)cob_display(0,1,1,&f_14)
```
can you turn it off please?

**Comment by brunopacheco1** [comment]
@OlegKunitsyn This is another side effect caused by calling cob_display to get cob field values from GC without doing the parsing in the extension. I'm going to open a new ticket to revert these changes to what was before.

**Comment by GitMensch** [comment]
@brunopacheco1 thank you for the extension setting, works quite well.
Can you please adjust the result?

Instead of the current variant having the value as a sub-item:
![current way with sub-entry](https://user-images.githubusercontent.com/6699539/87053265-0baf9180-c202-11ea-85c6-248b80d336e7.png)

It would be nice to have it directly
![value only](https://user-images.githubusercontent.com/6699539/87053586-6cd76500-c202-11ea-9ddb-a8d90658ec73.png)
