### ISSUE TITLE
No display shown when running code from VS Code running on WSL

### ISSUE THREAD

**Issue by gfmoore** [OlegKunitsyn/gnucobol-debug#5]
Ok, I am using WSL2 (windows 10 linux subsystem). I have installed gdb 7.6.1, gnu cobol 2.2.0
I can manually compile and run my payroll.cob program (just a test) using cobc -xj payroll.cob and I get output fine - 4 lines.

I now start visual studio code (insiders) from within wsl using code .
This launches vs code, open folder, bring up payroll.cob, nicely displayed (using bitlang cobol (colouriser) and Broadcom language support). Debug code and though the debug toolbar displays briefly there is no output. Try opening output using the view menu, nothing seen.
I also cannot click in the left hand field to get a breakpoint.

I think it's working, but not displaying. Not sure about breakpoint though

launch.json is
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    
    {
      "name": "COBOL debugger",
      "type": "gdb",
      "request": "launch",
      "target": "${file}",
      "cwd": "${workspaceRoot}",
      "gdbpath": "gdb",
      "cobcpath": "cobc"
    }
  ]
}

Can I provide anything else.

This is not a deal breaker for me, just playing with COBOL. 
Gordon :)

edit: uhmmm. I just checked using the terminal (powershell) from the vs code ide and gnu cobc doesn't seem to be installed from that perspective. I tried sudo apt install gnucobol from that terminal, but it wouldn't have a bar of it. Uhmm, bit confused. I wonder if vs code is still using a windows environment even though launched from within ubuntu/wsl?

Well that is weird. I tried opening code from cmder, (a nice cmd) (bash, then  code .). It seemed to load a different version of code. This worked fine, so I'm all good now.
Hope this helps someone else.
I'll close the issue. (Funny how you can often find a solution after posting an issue! Must help the brain process things writing it down.)

**Comment by GitMensch** [comment]
> Funny how you can often find a solution after posting an issue! Must help the brain process things writing it down.

It definitely does. In 80%  of the time you actually need to press "post", too.
Thanks for the Q+A style note.

To answer the question: vscode on Win10 is a win32 executable. If you have it in path you can execute it from wsl, but it will still only see the win32 environment the wsl environment was originally started (you may pass some variables around with WSLENV).

The way it could work is if you change the `cobc` command from vscode to invoke the wsl environment something like `bash.exe cobc param1 param2` - @gfmoore  please try this and report back. For debugging you'd have to start the process to run similar and then attach to GDB using the PID of the started process.

**Comment by gfmoore** [comment]
I think, that I've now downloaded VS Code under the wsl2 ubuntu and that's now what is running. - it is starting to confuse me as to what is going on! lol

regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 10:07:49, Simon Sobisch <notifications@github.com> wrote:
Funny how you can often find a solution after posting an issue! Must help the brain process things writing it down.
It definitely does. In 80% of the time you actually need to press "post", too.
Thanks for the Q+A style note.
To answer the question: vscode on Win10 is a win32 executable. If you have it in path you can execute it from wsl, but it will still only see the win32 environment the wsl environment was originally started (you may pass some variables around with WSLENV).
The way it could work is if you change the cobc command from vscode to invoke the wsl environment something like bash.exe cobc param1 param2 - @gfmoore [https://github.com/gfmoore] please try this and report back. For debugging you'd have to start the process to run similar and then attach to GDB using the PID of the started process.

**Comment by GitMensch** [comment]
WSL2 has native support for GUIs?

**Comment by gfmoore** [comment]
yes, you can run vs code from inside wsl2 and it works. It is the native linux gui. It's all getting amazing.... ;) Whatever next.

https://www.youtube.com/watch?v=MrZolfGm8Zk [https://www.youtube.com/watch?v=MrZolfGm8Zk] Microsoft bloke


regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 10:41:57, Simon Sobisch <notifications@github.com> wrote:
WSL2 has native support for GUIs?

**Comment by gfmoore** [comment]
Well to be more accurate it's running the gui using windows, but it all connects to the wsl linux - I think!

regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 10:41:57, Simon Sobisch <notifications@github.com> wrote:
WSL2 has native support for GUIs?

**Comment by brunopacheco1** [comment]
VSCode has a server side app running on WSL, which servers the linux environment, but the VSCode client is running on the Windows host. Please, refer to [VS Code Online](https://code.visualstudio.com/docs/remote/remote-overview).

**Comment by gfmoore** [comment]
Ahhh, I can see it now. I've had to reinstall Ubuntu 18.04. I had tried doing a hack upgrade to 19, but some things wouldn't work like snap. So I'm going to try again with vs code debug to see if it works now. Maybe some time as I have a meeting.

regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 13:29:09, Bruno Pacheco <notifications@github.com> wrote:
VSCode has a server side app running on WSL, which servers the linux environment, but the VSCode client is running on the Windows host. Please, refer to VS Code Online [https://code.visualstudio.com/docs/remote/remote-overview].

**Comment by gfmoore** [comment]
Don't forget to get wsl 2 running, a new install of Ubuntu seems to defer back to wsl 1

https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by gfmoore** [comment]
And you have to set metadata to allow permissions
https://docs.microsoft.com/en-us/windows/wsl/file-permissions
https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/
The screencast goes fast, but here is the code
in /etc/wsl.conf 

[network]
generateHosts = false

#mount with options
[automount]
options = "metadata"

hope this really helps someone :)
