### ISSUE TITLE
malformed linespec error: unexpected colon (from break-insert -f ":0")

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#53]
As I'm not sure if this was considered to be solved already I'm (possibly re-)posting this.

I always see this message when starting a debug session on this machine, specs:

cobc (GnuCOBOL) 3.1-dev.0 - Packaged  Apr 03 2020 18:23:45 UTC, C version "5.4.0 20160609"
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
gnucobol-debug v0.31.21

**Comment by GitMensch** [comment]
... "vanished" when removing all existing breakpoints and setting the ones for the existing files again, so maybe this issue only happens when a breakpoint is set in a file, then another file is used for debugging, the old file deleted and then the debugging restarted?
In this case the issue can likely be solved within the plugin.

**Comment by brunopacheco1** [comment]
I believe this issue is closed.
