### ISSUE TITLE
Remove call of cob_display

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#54]
In order to support different `usage` cases, like `numeric binary`, `double` and `float`, a call to `cob_display` was introduced, there so no parsing would be required in the extension side, keeping related complexities and one source of data to the GC.

These changes have introduced some side effects that are making our lives harder, like:
- Remote debugging is impossible as we don't have direct access to the running process output;
- Polluted console log (even when the verbose mode is `false`);
- Concurrency issues when writing to STDOUT (that didn't happen, but it is perfectly possible);
- Possible issues with STDOUT redirection (TO_STDERR equals to `false` or `cob_display(0,1,1, &field)`);

So, for the sake of stability and to unblock other tickets, the calling of `cob_display` should be removed and the values should be parsed again in the extension until we find another solution in the GC side.

**Comment by GitMensch** [comment]
> the values should be parsed again in the extension until we find another solution in the GC side

Would be necessary in any case as everything we use from the GC side would be a new GC feature and therefore not available with 2.2 (or 3.0-rc1 or old 3.1-dev).

Concerning the new GC solution - it would be good to know if the not-yet-written function could take a buffer + length and if it can't if it would be fine to return the same buffer (`const char *` unchanged, the content stored there changing after every call).
As soon as this is known I can adjust GC.

**Comment by brunopacheco1** [comment]
Could you provide both solutions so I could test them? Which one do you prefer the most?

**Comment by GitMensch** [comment]
> Could you provide both solutions so I could test them?

If possible I'd like to do it "right" when I know what _seems_ to work.
A minimal test would be something like (to be added to libcob/call.c)

```c
static int run = 0;
extern const char *
get_field_string (cob_field *f, const char *buffer, const size_t size)
{
	if (!buffer || !size) return "(error: bad buffer)";
	if (!f) return "(error: NULL field)";
	if (!f->data) return "(not allocated)";

	switch (run) {
		case 0:
			strncpy (buffer, "\"abc\"", size);
			break;
		case 1:
			strncpy (buffer, "12.3", size);
			break;
		case 2:
			strncpy (buffer, "0x123148", size);
			break;
		default:
			buffer[0] = 0;
			break;
	}
	run++;
	return buffer;
}

static int run_int = 0;
static size_t BUFF_INT = 512;
static char int_buffer[BUFF_INT + 1];
extern const char *
get_field_string_buffered (cob_field *f)
{
	if (!f) return "(error: NULL field)";
	if (!f->data) return "(not allocated)";

	switch (run_int) {
		case 0:
			strncpy (int_buffer, "\"abc\"", BUFF_INT);
			break;
		case 1:
			strncpy (int_buffer, "12.3", BUFF_INT);
			break;
		case 2:
			strncpy (int_buffer, "0x123148", BUFF_INT);
			break;
		default:
			int_buffer[0] = 0;
			break;
	}
	run_int++;
	return int_buffer;
}
```

> Which one do you prefer the most?

definitely the external provided buffer as it provides the most flexibility.

**Comment by brunopacheco1** [comment]
Sure no problem at all, I'll try on my side ASAP and I'll share with you my findings when I have something more concrete.

Thanks again for all support.

**Comment by brunopacheco1** [comment]
In my first try, I've got this error message when trying to compile the function `get_field_string`.

```
call.c:1996:14: error: assignment of read-only location ‘*buffer’
    buffer[0] = 0;
```

Removing the default clause makes the compilation working again.

**Comment by brunopacheco1** [comment]
As soon as I trying running manually several times the command `444-data-evaluate-expression "(char *) get_field_string(&f_11, \"\", 10)"`, it returns the following answers:

```
stdout: 444^done,value="0x7ffff79c01a0 \"\\\"abc\\\"\""
stdout: 444^done,value="0x7ffff79c01b0 \"12.3\""
stdout: 444^done,value="0x7ffff79c01c0 \"0x123148\""
```

So, I believe it is working as expected, and as it is the preferable choice, I will not test the other option.

**Comment by brunopacheco1** [comment]
@GitMensch following up the tests on a possible new function on GC, to get the string value of a cob_field, please find attached a log with the function called by the extension, and as expected, it is getting the string properly.

[VERBOSE.txt](https://github.com/OlegKunitsyn/gnucobol-debug/files/4828217/VERBOSE.txt)

**Comment by OlegKunitsyn** [comment]
@GitMensch I need these intrinsics in GC in order to integrate vscode unit-test api with gcblunit, without instrumenting C code:

- THROW an exception
- MODULE-CALLER-PATH
- MODULE-CALLER-SOURCE

**Comment by GitMensch** [comment]
I'm a bit confused, you are passing a constant string as buffer? Looks like it will trash the memory (you may find out more easily by copying a very long string in the prototype function).

I'd say you either find a way to create a buffer somehow and pass a different address per variable or we should use the non-preferred second option where my main question is: does it work at all, especially with watching two variables?

**Comment by GitMensch** [comment]
Interesting, although I fall to see how it is related to this issue.
You may want to create two feature requests for those, but I don't see that the first one will come before 4.0.

So you know that someone created a unit test framework for COBOL before without THROW that is hosted at GH, too?
I guess that a plain CALL would likely be working, too.

Simon

**Comment by brunopacheco1** [comment]
> I'm a bit confused, you are passing a constant string as buffer? Looks like it will trash the memory (you may find out more easily by copying a very long string in the prototype function).

What do you mean by that? Just a remark, It looks like every call is pointing to the same address, does it mean something?

> I'd say you either find a way to create a buffer somehow and pass a different address per variable or we should use the non-preferred second option where my main question is: does it work at all, especially with watching two variables?

This is my plan for today, I'll try to use more extensively the GDB Variable API.

**Comment by GitMensch** [comment]
> What do you mean by that?

The first method expects to gets an address of a `buffer` that it can write to up to `size`.
What I've seen is that you pass it a string constant (= a pointer to "somewhere" the runtime has placed a char array of size 2 with the content `'\\'` + `0`). As you've told it to GnuCOBOL will now write to _this place_, which is very likely a bad idea (as the storage there is to be considered "non-writeable").

> Just a remark, It looks like every call is pointing to the same address, does it mean something?

If the method "finds" a valid address (it can only do minimal checks) then it will return the address you've passed it back. As you currently pass always the same - likely "dirty"- address...
Remark: If you pass `NULL` or a non-allocated field (for example one that has the `BASED` attribute) you'll get a (non-writeable) constant from the GnuCOBOL runtime space, which should be a different address.

> This is my plan for today, I'll try to use more extensively the GDB Variable API.

OK, I'll hold back any changes so far.
Note: we have until Sunday to add new methods to GnuCOBOL 3.1 - so: no pressure but I'd like to know sooner than later which way we can go ;-)

**Comment by brunopacheco1** [comment]
@GitMensch Do you think the following commands are a good approach?

```
stdin: 555-var-create test 0 "(char *) malloc(100)"
stdout: 555^done,name="test",numchild="1",value="0x7ffff79c0280 \"\"",type="char *",has_more="0"
stdin: 444-data-evaluate-expression "(char *) get_field_string(&f_11, 0x7ffff79c0280, 100)"
stdout: 444^done,value="0x7ffff79c0280 \"12.3\""
````

For some unknown reason when I run `-var-evaluate-expression test` the output is `^done,value="0x7ffff79c0280 \"\""`, as if the function is not copying the new content to the buffer.

And if I run `-var-assign test "(char *) get_field_string(&f_11, 0x7ffff79c0280, 100)"` the output is `^error,msg="-var-assign: Variable object is not editable"`.

Well, I still believe this function is doable like it is. For me, it is just a matter of knowing what to do.

I'll keep trying to understand what is happening, but if you have a clue, please any support is welcomed.

**Comment by brunopacheco1** [comment]
BTW, the second function has the following response:

```
stdin: 111-data-evaluate-expression "(char *) get_field_string_buffered(&f_11)"
stdout: 111^done,value="0x7ffff7fc5760 <int_buffer> \"\\\"abc\\\"\""
```

It looks good either, but it goes straight to the point, let's say, as it doesn't require an extra argument and I don't have to define a buffer per variable to watch.

**Comment by GitMensch** [comment]
@brunopacheco1 Does watch work with the second approach, too - or do all variables are shown to be identical?
Note: I should be able to add this to the C API over the weekend, so it will be part of 3.1-rc1.

**Comment by brunopacheco1** [comment]
Sorry, I forgot to share the tests within the extension, but the variables were not sharing the same value.

I believe that is not happening because the presented value is the function return, not the value in memory. If the function is thread-safe or the MI commands are executed one by one (not in parallel), we don't have to worry about it.

**Comment by GitMensch** [comment]
OK, I'll go with the direct display (and likely add the other as option).
Note: the function can not be thread safe as this would require to pass a pre-created "environment" in, otherwise it will never be thread-safe as the internal buffer is always the same and therefore you'll always have the option to return from the function while another function call is already coming in and adjusting the buffer.

**Comment by brunopacheco1** [comment]
Sure, what I meant was if there's any concurrency happening when calling `get_field_string_buffered()`, which will use an internal buffer, we would have issues when presenting the variable in the panel. But it looks like this isn't the case as we didn't have any concurrency issue during the period we had the `cod_display` to gather the variable values.

**Comment by brunopacheco1** [comment]
So, I will close this issue and open a new one to refer to this topic of supporting usage cases.

**Comment by GitMensch** [comment]
> So, I will close this issue ...

agreed

> ... and open a new one to refer to this topic of supporting usage cases.

That's actually #30 :-)
