### ISSUE TITLE
Debugger not allowing breakpoints

### ISSUE THREAD

**Issue by gfmoore** [OlegKunitsyn/gnucobol-debug#6]
VS Code running from wsl (Ubuntu 18.04)

Hi, I cannot seem to get a breakpoint against any line of my COBOL code.
I tried on DISPLAY line, but no joy.
![image](https://user-images.githubusercontent.com/22768967/80078649-1e8dc080-8547-11ea-8942-13f880667a9f.png)

**Comment by OlegKunitsyn** [comment]
Please check v. 0.6.22 out. Still the same?

**Comment by gfmoore** [comment]
okay, remember I'm running this from within a wsl bash shell using code . but reading a windows folder (I'm on wsl 2 so should? be okay).
Uninstalled, reload, installed, reload, debug F5 bang!
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    
    {
      "name": "COBOL debugger",
      "type": "gdb",
      "request": "launch",
      "target": "${file}",
      "cwd": "${workspaceRoot}",
      "gdbpath": "gdb",
      "cobcpath": "cobc"
    }
  ]
}




regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 17:19:23, OlegKunitsyn <notifications@github.com> wrote:
Please check v. 0.6.22 out. Still the same?

**Comment by mitsakosgr** [comment]
I still have the same problem. On Linux system and using Remote - SSH.

I tried completely removing the plugins and settings but the problem remains.

**Comment by gfmoore** [comment]
Hi,

why do computers act so illogically!!! :sigh

Anyhow, I uninstalled all extensions, created a new folder, did some other stuff with wsl 2 that nearly killed my computer - no desktop!!!

Any how I am trying running bash from cmd, well actually cmder and run code . I load the extensions
I get 


so it says it can't start debugger. het if I run a terminal and do gdb --version, it looks fine


It looks pretty close.

The reason I check that i'm on wsl 2 is that if it isn't set then I can't read or write to a windows share. (There is something a bit flaky about it imho - but it is on insiders.)

Something else that seems a bit weird is that there are a number of ways of getting into WSL:
start ubuntu
shift right click on a folder and Open Linix shell
my usual method which is right click, run cmdr (or cmd) and bash
You can also do start menu and bash
I think you can powershell v7 as well.

I have a feeling that some may be slightly different in how they handle vs code. Does ubuntu and vscode . actually install a linix version of vs code and the others run the windows version with the wsl?

I need to find time to read that link you sent. Let me go find it.

One thing that I'm wondering about is do I need to be in an elevated privilege? I'll have a go...

If you start cmd with administrator privilege, cd to folder, code . it runs vs code, but not the wesl version.I can click on the bottom left and reopen in wsl, but then we're back to the above.


regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 19:27:00, Dimitris Pappas <notifications@github.com> wrote:
I still have the same problem. On Linux system and using Remote - SSH.
I tried completely removing the plugins and settings but the problem remains.

**Comment by gfmoore** [comment]
Hi,

I just tried from ubuntu, running code . then navigating to my windows folder and debugging - slightly different output on debug window

WARNING: Utility Command Server: Error in command socket Error: listen EACCES: permission denied C:\Users\Gordon\AppData\Local\Temp\gnucobol-debug-sockets\debug-instance-j6ml
WARNING: The examine memory location command won't work

Don't know if this helps or I'm muddying the water :(


regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 19:27:00, Dimitris Pappas <notifications@github.com> wrote:
I still have the same problem. On Linux system and using Remote - SSH.
I tried completely removing the plugins and settings but the problem remains.

**Comment by gfmoore** [comment]
Hi,

cleared everything out, used an old version and got it debugging again...

Now as to breakpoints. I assume as per normal I should be able to click in the line number area and get a red dot?

For the record I eventually noted thatthere are two sectiona in the vs code extensions area - one for local and one for wsl ubuntu 18.04

So now I have just the one wsl extension int he local, and your debigger in the wsl extension area. 

I'm going to bed!

regards,

Gordon
gm@gordonmoore.co.uk

On 23/04/2020 17:19:23, OlegKunitsyn <notifications@github.com> wrote:
Please check v. 0.6.22 out. Still the same?

**Comment by GitMensch** [comment]
Note: you may want to try to update GnuCOBOL to 3.1-dev (see the GnuCOBOL website how to do it) and compile your programs with `-fgen-c-line-directives`, this would allow "native" GDB to set a working breakpoint on every COBOL source line - but I don't know if this confuses the plugin in any way.

**Comment by gfmoore** [comment]
I've managed to compile the gnucobol-3.1-dev so at least I know that that works as a compiler, but I have no idea how to add the additional  compiler option. I would have thought it goes in the Makefile? but that is so complex I have no idea where to put it. I'm guessing there is an easier way. Sorry I'm not a linux developer.

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 05:28:03, Simon Sobisch <notifications@github.com> wrote:
Note: you may want to try to update GnuCOBOL to 3.1-dev (see the GnuCOBOL website how to do it) and compile your programs with -fgen-c-line-directives, this would allow "native" GDB to set a working breakpoint on every COBOL source line - but I don't know if this confuses the plugin in any way.

**Comment by mitsakosgr** [comment]
I think it has to do with the recognized language of VS Code. What other extensions you currently have to recognize cobol language?

I currently have `bitlang.cobol` for language support and VSCode recognize language as COBOL!
![1](https://user-images.githubusercontent.com/1503536/80190126-6c282d00-861c-11ea-8cb7-676efa86fa04.png)

If I change language to something that I have a debugger (ex C#) then it allows me to add breakpoints, and if I switch back to COBOL then debug works (not stepping, but it pause on breakpoints).

![2](https://user-images.githubusercontent.com/1503536/80190409-f07ab000-861c-11ea-893b-94db8563334c.png)

![3](https://user-images.githubusercontent.com/1503536/80190420-f2447380-861c-11ea-9d93-b7d7de81621c.png)

**Comment by gfmoore** [comment]
Heyup,
I apologise as I have found the issue as to why I couldn't get my program to compile properly with the v6.22 of the debugger. It didn't like the * in the 7th column. Took these out and debugger worked.
In my defence! v0.5.22 worked fine with them - go figure.
However, I still can't seem to set breakpoints, at least not with red dot that I expect. Is COBOL different?
So sorry.

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 09:16:06, Dimitris Pappas <notifications@github.com> wrote:
I think it has to do with the recognized language of VS Code. What other extensions you currently have to recognize cobol language?
I currently have bitlang.cobol for language support and VSCode recognize language as COBOL!
[1] [https://user-images.githubusercontent.com/1503536/80190126-6c282d00-861c-11ea-8cb7-676efa86fa04.png]
If I change language to something that I have a debugger (ex C#) then it allows me to add breakpoints, and if I switch back to COBOL then debug works (not stepping, but it pause on breakpoints).
[2] [https://user-images.githubusercontent.com/1503536/80190409-f07ab000-861c-11ea-893b-94db8563334c.png]
[3] [https://user-images.githubusercontent.com/1503536/80190420-f2447380-861c-11ea-9d93-b7d7de81621c.png]

**Comment by GitMensch** [comment]
> I've managed to compile the gnucobol-3.1-dev so at least I know that that works as a compiler, ...

Congrats!

> ... but I have no idea how to add the additional  compiler option. I would have thought it goes in the Makefile? but that is so complex I have no idea where to put it. I'm guessing there is an easier way. 

No, it is about any option you want to specify for `cobc`, I *guess* there is a json file this plugin uses to specify the compile command. If you can also debug without previous compilation from the editor you could also compile your source on WSL `cobc -g -fgen-c-line-directives prog.cob` and then "only" run the debugger.

**Comment by gfmoore** [comment]
Thanks for that, I'll try and see how to incorporate it.

But something very weird is going on with vs code and the debugger.
Here is a simple program, taken from http://www.csis.ul.ie/cobol/course/COBOLIntro.htm [http://www.csis.ul.ie/cobol/course/COBOLIntro.htm]


So I input 3, 4 they get changed to 7, 8. This happens whatever numbers I input.

Can you also see the two Canceled lines?Which I don't get with my other test program Payroll. 

Yet when I compile outside the debugger, at the command prompt it works fine:



So sorry about this. I am new to COBOL, just decided to learn it as a laugh as I missed out on it in the 70s when I were a lad :), I learnt Fortran IV instead. However, something very odd is going on. 

If this is just me being an idiot then I'm sorry for the bother. Might be better putting this on StackOverflow perhaps?

regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 09:56:19, Simon Sobisch <notifications@github.com> wrote:
I've managed to compile the gnucobol-3.1-dev so at least I know that that works as a compiler, ...
Congrats!
... but I have no idea how to add the additional compiler option. I would have thought it goes in the Makefile? but that is so complex I have no idea where to put it. I'm guessing there is an easier way.
No, it is about any option you want to specify for cobc, I guess there is a json file this plugin uses to specify the compile command. If you can also debug without previous compilation from the editor you could also compile your source on WSL cobc -g -fgen-c-line-directives prog.cob and then "only" run the debugger.

**Comment by mitsakosgr** [comment]
> > I've managed to compile the gnucobol-3.1-dev so at least I know that that works as a compiler, ...
> 
> Congrats!
> 
> > ... but I have no idea how to add the additional  compiler option. I would have thought it goes in the Makefile? but that is so complex I have no idea where to put it. I'm guessing there is an easier way.
> 
> No, it is about any option you want to specify for `cobc`, I _guess_ there is a json file this plugin uses to specify the compile command. If you can also debug without previous compilation from the editor you could also compile your source on WSL `cobc -g -fgen-c-line-directives prog.cob` and then "only" run the debugger.

Compiler (cobc) is run using the following arguments ([run arguments](https://github.com/OlegKunitsyn/gnucobol-debug/blob/17b140e0bd07ec41df42a5e35f1bd5bd40e8288d/src/mi2.ts#L70)):
`-free -x -g -d -fdebugging-line -fsource-location -ftraceall`

The -free option is causing the errors with the comments. It supports comments (even inline) with "*>".

**Comment by mitsakosgr** [comment]
@gfmoore 
stdin is not currently working
[Console input is not working correctly when running on debug mode](https://github.com/OlegKunitsyn/gnucobol-debug/issues/8#issuecomment-618497283)

Please keep this issue about breakpoints and not general questions!

**Comment by gfmoore** [comment]
Hi, I have now just spent an hour looking into VS Code's launch.json script. Not that much out there is helpful for what I am trying to do.
 Quote: I guess there is a json file this plugin uses to specify the compile command. If you can also debug without previous compilation from the editor you could also compile your source on WSL cobc -g -fgen-c-line-directives prog.cob and then "only" run the debugger.


{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "COBOL debugger",
      "type": "gdb",
      "request": "launch",
      "target": "${file}",
      "cwd": "${workspaceRoot}",
      "gdbpath": "gdb",
      "cobcpath": "cobc",
      "verbose": true,
      "group": []
    }
  ]
}

The only thing is that I cannot see how to add the compiler options in the launch.json.

Nothing I've tried even gets close. You can see the cobcpath attribute pointing at cobc, but you can't add compiler options here? I assume the extension has code that deals with this? Oh I added the verbose argument, not that it helped me.

This is starting to get so frustrating, but hey, thanks so much for all your help :)



regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 09:56:19, Simon Sobisch <notifications@github.com> wrote:
I've managed to compile the gnucobol-3.1-dev so at least I know that that works as a compiler, ...
Congrats!
... but I have no idea how to add the additional compiler option. I would have thought it goes in the Makefile? but that is so complex I have no idea where to put it. I'm guessing there is an easier way.
No, it is about any option you want to specify for cobc, I guess there is a json file this plugin uses to specify the compile command. If you can also debug without previous compilation from the editor you could also compile your source on WSL cobc -g -fgen-c-line-directives prog.cob and then "only" run the debugger.

**Comment by gfmoore** [comment]
Ahhh ok.

Sorry about going off topic.
I didn't see your response before i posted my last post about compiler options, now I see where they are (as I thought in your code.)
Didn't know there was an issue with console. thanks for the response with comments.

So, on this issue, still left with breakpoints not showing or working, and I'll leave it that and wait for a fix :)


regards,

Gordon
gm@gordonmoore.co.uk

On 24/04/2020 10:29:30, Dimitris Pappas <notifications@github.com> wrote:
@gfmoore [https://github.com/gfmoore]
stdin is not currently working
Console input is not working correctly when running on debug mode [https://github.com/OlegKunitsyn/gnucobol-debug/issues/8#issuecomment-618497283]
Please keep this issue about breakpoints and not general questions!

**Comment by OlegKunitsyn** [comment]
I've added COBOL dialects such as `COBOL`, `ACUCOBOL`, `OpenCOBOL`, `GnuCOBOL`, `entcobol`since v. 0.7.22 and tested woth `ibm.zopeneditor`, `broadcommfd.cobol-language-support`, `rechinformatica.rech-editor-cobol` or `bitlang.cobol`. Otherwise, VS Code treats the sources as plaint-text and breakpoints are unavailable. Readme updated. Please check this out.

**Comment by GitMensch** [comment]
@gfmoore said
>  still left with breakpoints not showing or working

That's fixed for you now, correct? Then please close the issue.
