### ISSUE TITLE
request for adjustments in launch configuration

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#66]
I suggest the following changes, which will need both adjustments in package.json (easy) and the code (less easy) and a possible hint to the user for updating (possibly hard). I argue to do these as early as possible to have less installations affected.

* make `gdbpath`, `cobcpath`, `cwd`, `group` and `targetargs` optional (they are currently required, while they will mostly be either empty or set to gdb/cobc)
* rename `targetargs` to `arguments` and possibly change it to `string` instead of an array
* drop `cobcpath`, `cobcargs` and `group`, instead reference a `preLaunchTask`  - so a freely adjustable entry in tasks.json; this one may also be provided by this extension, possibly defaulting to `cobc -x $(file)` but can easily be changed to `make` - which will also fix #63 without adding additional logic to this extension (there are free make implementations on every system vscode supports including for Windows where VS-people often have nmake or other make implementations from additional build systems installed); this also fixes to have the compiler setup multiple times, both for debugging and for "normal" compilation

**Comment by brunopacheco1** [comment]
@GitMensch I have done some changes in the extension launch configuration, to tackle the first and second bullet of your initial list.

The third point, about detaching the compilation from the debug session launch/attach, I believe it should be scoped to the #63 .

**Comment by OlegKunitsyn** [comment]
The keyword can not be completely renamed in the code:
>Invalid use of 'arguments'. Modules are automatically in strict mode.

I prepare 2.x, without deprecation mark.

**Comment by brunopacheco1** [comment]
So, the solution is to rename the field back to `targetargs` or just `args`.

**Comment by GitMensch** [comment]
I'd vote for args.

**Comment by brunopacheco1** [comment]
Me too.

**Comment by OlegKunitsyn** [comment]
I vote for speaking names. Cobolargs and targetargs addressed concrete things. I have renamed the property to 'arguments', but internally keep *args as they are, concrete. I see no advantages having abstract 'args'. Please clarify pros/cons.

**Comment by GitMensch** [comment]
There is only one args for the debugging itself - the one for the program to be started (if not attaching).
As explained before the debugging extension itself should not compile anything itself, this is a completely different tasks to run (the prelaunch option may come from vscode or from the extension - I'd have to check that) so no need for a compile arg at all.
args is quite common, but I'm fine with a long name as arguments/targetArguments to be more speaking (actually the description is used for that in vscode).

**Comment by brunopacheco1** [comment]
I agree with @GitMensch as the arguments would be the only argument configuration, but actually it is not the only one yet. Even the others are not mandatory and not visible anymore, but still, they are there to be used. I put the old name back.

**Comment by GitMensch** [comment]
As all entries but the "split compile from debug via launch task", which is tracked in #63 are solved and released I'm closing this now.
