### ISSUE TITLE
Table variables are not presented as an array of values

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#7]
VSCode 1.45.0-insider
Windows on WSL 2 (Debian)
cobc (GnuCOBOL) 2.2.0
GNU gdb (Debian 8.2.1-2+b3) 8.2.1

![image](https://user-images.githubusercontent.com/4491850/80095565-6e30b400-8568-11ea-9e0d-8789fa44bd2f.png)

On variables, WS-ITEM is a table (array).

[Sample repo](https://github.com/brunopacheco1/cobol-hello-world/blob/master/petstore.cbl)

**Comment by GitMensch** [comment]
Duplicate of #4

**Comment by brunopacheco1** [comment]
Closing it.
