### ISSUE TITLE
Confirm if it is possible to listen to changes on the extension settings

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#73]
As far as I know the debug action bar cannot be modified, only some additional actions be activated (I'd like the reverse step for example). Also I think it is too special to place it there.
Maybe we can register a callback for  changes in the settings instead?

_Originally posted by @GitMensch in https://github.com/OlegKunitsyn/gnucobol-debug/issues/40#issuecomment-659439614_

**Comment by brunopacheco1** [comment]
It is possible to check the current value of the settings each time we build the Variable Panel, but it is not possible to force the panel to be rebuilt each time we change the settings.

That means, if you toggle the settings, it will be applied after you execute a step. @GitMensch what do you think?

**Comment by GitMensch** [comment]
sounds good
