### ISSUE TITLE
What to do with RETURN-CODE variable

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#79]
@OlegKunitsyn thanks for checking this one.

@GitMensch should the developer be able to set the RETURN-CODE variable? Should we present it at all?

**Comment by GitMensch** [comment]
I assume this is a follow on to https://github.com/OlegKunitsyn/gnucobol-debug/pull/78#issuecomment-662230399.

And yes - I think the developer should be able to set any register that isn't read-only (if I remember correctly GnuCOBOL doesn't have one); `RETURN-CODE` can normally be set in COBOL debuggers for environments that have it.
Note: Programs are not guaranteed to have a `RETURN-CODE` (but if it hasn't then you shouldn't found it in the generated code in any case).

As I'm a bit confused: is the current master stable to self-build and use with GC 3.1rc1+ or is this a showstopping issue?

**Comment by brunopacheco1** [comment]
> I assume this is a follow on to [#78 (comment)](https://github.com/OlegKunitsyn/gnucobol-debug/pull/78#issuecomment-662230399).

Yes.

> As I'm a bit confused: is the current master stable to self-build and use with GC 3.1rc1+ or is this a showstopping issue?

It depends on @OlegKunitsyn , as he commented out: "Breakpoints fail", and I am not sure what he meant.

If this is just related to the RETURN-CODE variable, I believe this shouldn't be a blocker issue, and that is why I opened a new issue, to tackle it in another moment.

**Comment by OlegKunitsyn** [comment]
![Screenshot from 2020-07-22 16-01-56](https://user-images.githubusercontent.com/2870028/88186015-f2143e00-cc34-11ea-8683-046b45b12c9e.png)

**Comment by brunopacheco1** [comment]
Does this exception happen when you just load the extension? 

Anyway, with the latest PR for handling RETURN-CODE (or any integer variable actually), this exception should be not happening in any circumstance.

**Comment by OlegKunitsyn** [comment]
Disappeared applying the PR

**Comment by GitMensch** [comment]
I suggest closing this issue then :-)

As the CI to create the vsix is missing I try to pull the changes in, manually build it via the new task, and do some tests.

Note: For _real_ tests (which I originally want to do) I'd need the option in the launch to specify where C sources are and if they should be regenerated; at least for the attach scenario [where it is (obviously?) a bad idea to recreate the binary of the running program in any case]) - can someone of you try to add this or has this to be part of my learning (and by that moving the "real test" to the future)?
