### ISSUE TITLE
Console input is not working correctly when running on debug mode

### ISSUE THREAD

**Issue by brunopacheco1** [OlegKunitsyn/gnucobol-debug#8]
VSCode 1.45.0-insider
Windows on WSL 2 (Debian)
cobc (GnuCOBOL) 2.2.0
GNU gdb (Debian 8.2.1-2+b3) 8.2.1

![image](https://user-images.githubusercontent.com/4491850/80096234-88b75d00-8569-11ea-82d2-4b0e0e7df264.png)

When running this [sample](https://github.com/brunopacheco1/cobol-hello-world/blob/master/petstore.cbl) on debug mode, the console doesn't stop the loop after inserting "N".

**Comment by GitMensch** [comment]
I *guess* that roots in the non-free, half-binary WSL extension you use, not in this extension or the underlying GnuCOBOL installation.

You may try to run the process in WSL but use a native GDB version (for example from the MinGW project) to attach to the running WSL pid instead or, as you already use a recent (3.1-dev) official MinGW package of GnuCOBOL (includes GDB 7.6), you find those at https://www.arnoldtrembley.com/GnuCOBOL.htm, likely needs minimal more setup (*maybe* only the setup of PATH before you start vscode) [please document your findings, @OlegKunitsyn could include those in the documentation] but should work much better than a sub-system (WSL) or VM (WSL2) solution, *especially* if you primarily would setup those and the non-free WSL extensions to use GnuCOBOL and vscode.

**Comment by brunopacheco1** [comment]
Thanks, I'll double-check that.

I would say the problem is related to VS Code anyway either the remote client, the debugger, or the extension. WSL 2 is a VM, so there's nothing between the gdb and the VS Code debugger client, only the network. If I compile and run the code using VSCode terminal, it works properly, BTW.

**Comment by OlegKunitsyn** [comment]
Yes, stdin does not work via vscode console yet.

**Comment by gfmoore** [comment]
So, is this a vs code issue or a debugger issue?

**Comment by OlegKunitsyn** [comment]
Now you can execute (CTRL+F5) a program and use DEBUG CONSOLE as an input. Debugging (F5) with input is unstable at the moment.

**Comment by gfmoore** [comment]
Sorry, but didn't work for me? I suspect my code? which works from bash shell fine.


regards,

Gordon
gm@gordonmoore.co.uk

On 26/04/2020 11:43:36, OlegKunitsyn <notifications@github.com> wrote:
Now you can execute (CTRL+F5) a program and use DEBUG CONSOLE as an input. Debugging (F5) with input is unstable at the moment.

**Comment by OlegKunitsyn** [comment]
Fixed by v. 0.22.9. Please re-create launch.json.

**Comment by gfmoore** [comment]
0.22.9  Way to go! :)
This works fine yay!

Well done with all your hard work, very much appreciated. Now I can go and follow the course lol
Gordon
