### ISSUE TITLE
Docker selector

### ISSUE THREAD

**Issue by OlegKunitsyn** [OlegKunitsyn/gnucobol-debug#82]
Some programs valid for GC 2.2. are not compiling in GC 3.0 or GC 3.1. For now, Docker image is hardcoded to `gnucobol:3.1-dev`. I would like to change `"container": "gnucobol"` property to the list of: 
- `"container": "gnucobol:3.1-dev"` by default
- `"container": "gnucobol:3.0"`
- `"container": "gnucobol:2.2"`

What do you think about?

**Comment by GitMensch** [comment]
In general this shouldn't be a list but an URL, possibly with the newest one as default.
Reasoning: people would like to use their own docker containers which have additional tools installed.

side note: there's work in progress on alpine (actually on adelie, but this will be pushed to alpine afterwards) to have gnucobol available via the system package manager - which will make the container setup more simple, too.

Some programs valid for 3.1 will not be valid for 2.2 - but not the other way around. The _only_ exception are newer reserved words which may need to be undefined via `-fnot-reserved=word1,word2`. 
Please post to the bug list or issue tracker or discussion board for any program that compiled before and now doesn't (actually we provided the 3.1rc1 to catch those issues and fix them before 3.1 final - but that's only possible when we do get reports...)

**Comment by GitMensch** [comment]
Just to add the reference: fixed with 553a888f08cbc253c8bced9c5ef9370528dae0c5
