### ISSUE TITLE
launch.json "free" source format and dialect

### ISSUE THREAD

**Issue by mitsakosgr** [OlegKunitsyn/gnucobol-debug#9]
It would be nice to be able to select the free source format if wanted and command line arguments for the compiler.

It could be have default parameter "free: true" but somebody could change it if wanted.

**Comment by GitMensch** [comment]
two people writing the same at once... #10 is a duplicate of this

**Comment by mitsakosgr** [comment]
Closing this as #10 is way more descriptive!
Also working on a possible PR for this.

**Comment by GitMensch** [comment]
Thank you for working on the PR! You may want to have a look at #3, too.
